#include "StdAfx.h"
#include "ConstsString.h"
#include "leudgrid/ToolsMemFile.h"
#include "GameServerLib.h"

namespace OGSLib
{
	bool ConstsString::Load(GameServerLib* gslib)
	{
		char temp[1024];
		size_t size= 0;
		const char* data = gslib->GetListener()->LoadFile("infostring.txt",size);
		if( data && size > 0 )
		{
			LEUD::ToolsMemFile f(data,size);
			char line[1204];
			char key[1024];
			char value[1024];
			while( f.read_line(line,1024) )
			{
				if( line[0]!=0 )
				{
					if( line[0] == '#' || line[0] == ';' )
					{
						continue;
					}
					if( 2 == sscanf_s(line,"%[^=]=%[^\"]",key,_countof(key),value,_countof(value)) )
					{
						UtilString::act_2_utf8(value,strlen(value),temp,1024);
						strcpy_s(value,temp);
						mStringMap[key]=value;
					}
				}
			}
		}
		reload_key(NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP,"NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP");
		reload_key(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY,"NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY");
		reload_key(NOTIFY_BING_ITEM_LIMIT,"NOTIFY_BING_ITEM_LIMIT");
		reload_key(NOTIFY_BEYOND_ONSALE_LIMIT,"NOTIFY_BEYOND_ONSALE_LIMIT");
		reload_key(NOTIFY_ONSALE_TIME_ERROR,"NOTIFY_ONSALE_TIME_ERROR");
		reload_key(NOTIFY_ONSALE_ITEM_MISS,"NOTIFY_ONSALE_ITEM_MISS");
		reload_key(NOTIFY_ONSALE_MAX_LIMIT,"NOTIFY_ONSALE_MAX_LIMIT");
		reload_key(NOTIFY_ONSALE_PUT_SUC,"NOTIFY_ONSALE_PUT_SUC");
		reload_key(NOTIFY_ONSALE_OWNER_OFFLINE,"NOTIFY_ONSALE_OWNER_OFFLINE");
		reload_key(NOTIFY_ONSALE_MIN_LEVEL_LIMIT,"NOTIFY_ONSALE_MIN_LEVEL_LIMIT");
		reload_key(NOTIFY_ONSALE_ITEM_SUC,"NOTIFY_ONSALE_ITEM_SUC");
		reload_key(NOTIFY_ONSALE_ITEM_CANNOT,"NOTIFY_ONSALE_ITEM_CANNOT");
		reload_key(NOTIFY_ONSALE_FREE_LIMIT,"NOTIFY_ONSALE_FREE_LIMIT");
		reload_key(NOTIFY_ONSALE_MONEY_LIMIT,"NOTIFY_ONSALE_MONEY_LIMIT");
		reload_key(NOTIFY_MERGE_FASHION_CONDITION_FAIL,"NOTIFY_MERGE_FASHION_CONDITION_FAIL");
		reload_key(NOTIFY_MERGE_XYFASHION_CONDITION_FAIL,"NOTIFY_MERGE_XYFASHION_CONDITION_FAIL");
		reload_key(NOTIFY_ITEM_DESTORY_LIMIT_FAIL,"NOTIFY_ITEM_DESTORY_LIMIT_FAIL");
		reload_key(NOTIFY_SPLIT_BAG_FULL_FAIL,"NOTIFY_SPLIT_BAG_FULL_FAIL");
		reload_key(NOTIFY_MAIL_RECEIVE_SUC,"NOTIFY_MAIL_RECEIVE_SUC");
		reload_key(NOTIFY_MAIL_HAVE_RECEIVED,"NOTIFY_MAIL_HAVE_RECEIVED");
		reload_key(NOTIFY_MAIL_DELETE_SUC,"NOTIFY_MAIL_DELETE_SUC");
		reload_key(NOTIFY_MAIL_EXCEED_MAX_LENGTH,"NOTIFY_MAIL_EXCEED_MAX_LENGTH");
		reload_key(NOTIFY_MAIL_DELETE_UNRECEIVED,"NOTIFY_MAIL_DELETE_UNRECEIVED");
		reload_key(NOTIFY_MAIL_NOT_EXIST,"NOTIFY_MAIL_NOT_EXIST");
		reload_key(NOTIFY_BAG_BLANK_NOT_ENOUGH,"NOTIFY_BAG_BLANK_NOT_ENOUGH");
		reload_key(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND,"NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND");
		reload_key(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN,"NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN");
		reload_key(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND,"NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND");
		reload_key(NOTIFY_USE_TIEM_LIMIT_ERROR,"NOTIFY_USE_TIEM_LIMIT_ERROR");
		reload_key(NOTIFY_ZHUANSHENG_LEVEL_LIMIT,"NOTIFY_ZHUANSHENG_LEVEL_LIMIT");
		//reload_key(NOTIFY_USE_ITEM_LIMIT_MAXLOAD,"NOTIFY_USE_ITEM_LIMIT_MAXLOAD");
		//reload_key(NOTIFY_USE_ITEM_LIMIT_MAXBRAWN,"NOTIFY_USE_ITEM_LIMIT_MAXBRAWN");
		reload_key(NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR,"NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR");
		reload_key(NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY,"NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY");
		reload_key(NOTIFY_NOT_ENOUPH_MP,"NOTIFY_NOT_ENOUPH_MP");
		reload_key(NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP,"NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP");
		reload_key(NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN,"NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN");
		reload_key(NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP,"NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP");
		reload_key(NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE,"NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE");
		reload_key(NOTIFY_DROP_ITEM_CAN_NOT_BIND,"NOTIFY_DROP_ITEM_CAN_NOT_BIND");
		reload_key(NOTIFY_TRADE_ITEM_CAN_NOT_BIND,"NOTIFY_TRADE_ITEM_CAN_NOT_BIND");
		reload_key(NOTIFY_CHAT_TOO_QUICK,"NOTIFY_CHAT_TOO_QUICK");
		reload_key(NOTIFY_SKILL_YEMAN_FALIED,"NOTIFY_SKILL_YEMAN_FALIED");
		reload_key(NOTIFY_SKILL_CISHAJIANSHU_OPEN,"NOTIFY_SKILL_CISHAJIANSHU_OPEN");
		reload_key(NOTIFY_SKILL_CISHAJIANSHU_CLOSE,"NOTIFY_SKILL_CISHAJIANSHU_CLOSE");
		reload_key(NOTIFY_SKILL_BANYUEWANDAO_OPEN,"NOTIFY_SKILL_BANYUEWANDAO_OPEN");
		reload_key(NOTIFY_SKILL_BANYUEWANDAO_CLOSE,"NOTIFY_SKILL_BANYUEWANDAO_CLOSE");
		reload_key(NOTIFY_SKILL_LIEHUOJIANFA_OK,"NOTIFY_SKILL_LIEHUOJIANFA_OK");
		reload_key(NOTIFY_SKILL_COLDING,"NOTIFY_SKILL_COLDING");
		reload_key(NOTIFY_SKILL_SHUNJIANYIDONG_FAILED,"NOTIFY_SKILL_SHUNJIANYIDONG_FAILED");
		reload_key(NOTIFY_MERDER,"NOTIFY_MERDER");
		reload_key(NOTIFY_PK_KILLED,"NOTIFY_PK_KILLED");
		reload_key(NOTIFY_PK_MAP_NOT_MERDER,"NOTIFY_PK_MAP_NOT_MERDER");
		reload_key(NOTIFY_MAP_PK_PROHIBIT,"NOTIFY_MAP_PK_PROHIBIT");
		reload_key(NOTIFY_MAPTIME_PK_PROHIBIT, "NOTIFY_MAPTIME_PK_PROHIBIT");
		reload_key(NOTIFY_TRADE_TOO_FAR,"NOTIFY_TRADE_TOO_FAR");
		reload_key(NOTIFY_TRADE_CAN_NOT_AUTH_TYPE,"NOTIFY_TRADE_CAN_NOT_AUTH_TYPE");
		reload_key(NOTIFY_TRADE_CAN_NOT_LEVEL,"NOTIFY_TRADE_CAN_NOT_LEVEL");
		reload_key(NOTIFY_ITEM_USE_TIME_TOO_SHORT,"NOTIFY_ITEM_USE_TIME_TOO_SHORT");
		reload_key(NOTIFY_BAG_USE_ITEM_MAP_DISABLED,"NOTIFY_BAG_USE_ITEM_MAP_DISABLED");
		reload_key(NOTIFY_SKILL_MAP_DISABLED,"NOTIFY_SKILL_MAP_DISABLED");
		reload_key(NOTIFY_MERGESTEEL_SUC,"NOTIFY_MERGESTEEL_SUC");
		reload_key(NOTIFY_MERGESTEEL_FAL,"NOTIFY_MERGESTEEL_FAL");
		reload_key(NOTIFY_UPGRADEEQUIP_SUC,"NOTIFY_UPGRADEEQUIP_SUC");
		reload_key(NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT,"NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT");
		reload_key(NOTIFY_QILING_SUC,"NOTIFY_QILING_SUC");
		reload_key(NOTIFY_QILING_FULL,"NOTIFY_QILING_FULL");
		reload_key(NOTIFY_UPGRADEEQUIP_FAL,"NOTIFY_UPGRADEEQUIP_FAL");
		reload_key(NOTIFY_NOENOUGHMONEY_FAL,"NOTIFY_NOENOUGHMONEY_FAL");
		reload_key(NOTIFY_UPGRADE_MATCHSTONE_FAL,"NOTIFY_UPGRADE_MATCHSTONE_FAL");
		reload_key(NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT,"NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT");
		reload_key(NOTIFY_BUY_ITEM_NOT_YOUKE,"NOTIFY_BUY_ITEM_NOT_YOUKE");
		reload_key(NOTIFY_SKILL_YOULINGDUN,"NOTIFY_SKILL_YOULINGDUN");
		reload_key(NOTIFY_SKILL_SHENGZHANJIASHU,"NOTIFY_SKILL_SHENGZHANJIASHU");
		reload_key(NOTIFY_WORLD_CHAT_LEVEL_LIMIT,"NOTIFY_WORLD_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_GROUP_CHAT_LEVEL_LIMIT,"NOTIFY_GROUP_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_GUILD_CHAT_LEVEL_LIMIT,"NOTIFY_GUILD_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_MAP_CHAT_LEVEL_LIMIT,"NOTIFY_MAP_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT,"NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_HORN_CHAT_LEVEL_LIMIT,"NOTIFY_HORN_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_NORMAL_CHAT_LEVEL_LIMIT,"NOTIFY_NORMAL_CHAT_LEVEL_LIMIT");
		reload_key(NOTIFY_LOGIN_ANOTHER_PLACE,"NOTIFY_LOGIN_ANOTHER_PLACE");
		reload_key(NOTIFY_FRESH_VCOIN_WAIT,"NOTIFY_FRESH_VCOIN_WAIT");
		reload_key(NOTIFY_KICK_BUY_GM,"NOTIFY_KICK_BUY_GM");
		reload_key(NOTIFY_TALK_PROHIBITED,"NOTIFY_TALK_PROHIBITED");
		reload_key(NOTIFY_TALK_ALLOWED,"NOTIFY_TALK_ALLOWED");
		reload_key(NOTIFY_PK_KILL,"NOTIFY_PK_KILL");
		reload_key(NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD,"NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD");
		reload_key(NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD,"NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD");
		reload_key(NOTIFY_CONGZI_INFO,"NOTIFY_CONGZI_INFO");
		reload_key(NOTIFY_ADD_FRIEND_NO_EXIST,"NOTIFY_ADD_FRIEND_NO_EXIST");
		reload_key(NOTIFY_CHECK_EQUIP_NO_EXIST,"NOTIFY_CHECK_EQUIP_NO_EXIST");
		reload_key(NOTIFY_BUY_ITEM_BAG_FULL,"NOTIFY_BUY_ITEM_BAG_FULL");
		reload_key(NOTIFY_ITEM_BAG_FULL,"NOTIFY_ITEM_BAG_FULL");
		reload_key(NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN,"NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN");
		reload_key(NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE,"NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE");
		reload_key(NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE,"NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE");
		reload_key(NOTIFY_GROUP_MEMBER_ADD,"NOTIFY_GROUP_MEMBER_ADD");
		reload_key(NOTIFY_JOIN_GROUP,"NOTIFY_JOIN_GROUP");
		reload_key(NOTIFY_GROUP_MEMBER_REM,"NOTIFY_GROUP_MEMBER_REM");
		reload_key(NOTIFY_LEAVE_GROUP,"NOTIFY_LEAVE_GROUP");
		reload_key(NOTIFY_TRADE_FAIL,"NOTIFY_TRADE_FAIL");
		reload_key(NOTIFY_TRADE_SUC,"NOTIFY_TRADE_SUC");
		reload_key(NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR,"NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR");
		reload_key(NOTIFY_TRADE_PLAYER_OFFLINE,"NOTIFY_TRADE_PLAYER_OFFLINE");
		reload_key(NOTIFY_CHATTRADE_MYSELF,"NOTIFY_CHATTRADE_MYSELF");
		reload_key(NOTIFY_CHATTRADE_FAIL,"NOTIFY_CHATTRADE_FAIL");
		reload_key(NOTIFY_CHANGE_ATTACK_MODE_FAIL,"NOTIFY_CHANGE_ATTACK_MODE_FAIL");
		reload_key(NOTIFY_MAP_NOGOD, "NOTIFY_MAP_NOGOD");
		reload_key(NOTIFY_CHATTRADE_BAGFULL, "NOTIFY_CHATTRADE_BAGFULL");
		reload_key(NOTIFY_CHATTRADE_ADDITEM_SUC,"NOTIFY_CHATTRADE_ADDITEM_SUC");
		reload_key(NOTIFY_NO_FRIEND_ONLINE, "NOTIFY_NO_FRIEND_ONLINE");
		reload_key(NOTIFY_CHATTRADE_ADDITEM_FAIL,"NOTIFY_CHATTRADE_ADDITEM_FAIL");
		reload_key(NOTIFY_CHATTRADE_SUBITEM_SUC,"NOTIFY_CHATTRADE_SUBITEM_SUC");
		reload_key(NOTIFY_CHATTRADE_SUBITEM_NOITEM,"NOTIFY_CHATTRADE_SUBITEM_NOITEM");
		reload_key(NOTIFY_CHATTRADE_SUBITEM_FAIL,"NOTIFY_CHATTRADE_SUBITEM_FAIL");
		reload_key(NOTIFY_CHATTRADE_MONEY_NOTENOUGH,"NOTIFY_CHATTRADE_MONEY_NOTENOUGH");
		reload_key(NOTIFY_HUICHENGSHI_CISHU, "NOTIFY_HUICHENGSHI_CISHU");
		reload_key(NOTIFY_SLAVE_AI_OPEN,"NOTIFY_SLAVE_AI_OPEN");
		reload_key(NOTIFY_SLAVE_AI_CLOSE,"NOTIFY_SLAVE_AI_CLOSE");
		reload_key(NOTIFY_GUILD_CREATE_EMPTY_NAME,"NOTIFY_GUILD_CREATE_EMPTY_NAME");
		reload_key(NOTIFY_GUILD_CREATE_TOO_LONG_NAME,"NOTIFY_GUILD_CREATE_TOO_LONG_NAME");
		reload_key(NOTIFY_GUILD_CREATE_NAME_PROHIBITED,"NOTIFY_GUILD_CREATE_NAME_PROHIBITED");
		reload_key(NOTIFY_GUILD_CREATE_EXIST_NAME,"NOTIFY_GUILD_CREATE_EXIST_NAME");
		reload_key(NOTIFY_GUILD_CREATE_CONDITION_FAIL,"NOTIFY_GUILD_CREATE_CONDITION_FAIL");
		reload_key(NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR,"NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR");
		reload_key(NOTIFY_GUILD_CREATE_HAVE_GUILD,"NOTIFY_GUILD_CREATE_HAVE_GUILD");
		reload_key(NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR,"NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR");
		reload_key(NOTIFY_GUILD_JOIN_HAVED,"NOTIFY_GUILD_JOIN_HAVED");
		reload_key(NOTIFY_GUILD_JOIN_NOT_EXIST,"NOTIFY_GUILD_JOIN_NOT_EXIST");
		reload_key(NOTIFY_GROUP_MEMBER_ONLINE,"NOTIFY_GROUP_MEMBER_ONLINE");
		reload_key(NOTIFY_GROUP_MEMBER_OFFLINE,"NOTIFY_GROUP_MEMBER_OFFLINE");
		reload_key(NOTIFY_GUILD_MEMBER_ENTERING,"NOTIFY_GUILD_MEMBER_ENTERING");
		reload_key(NOTIFY_GUILD_ADD_PRESIDENT, "NOTIFY_GUILD_ADD_PRESIDENT");
		reload_key(NOTIFY_GUILD_SUB_PRESIDENT, "NOTIFY_GUILD_SUB_PRESIDENT");
		reload_key(NOTIFY_GUILD_BECOME_ADMIN, "NOTIFY_GUILD_BECOME_ADMIN");
		reload_key(GUILD_RED_PACKET_MAIL_TITLE, "GUILD_RED_PACKET_MAIL_TITLE");
		reload_key(GUILD_RED_PACKET_MAIL_CONTENT, "GUILD_RED_PACKET_MAIL_CONTENT");
		reload_key(NOTIFY_UPGRADEEQUIP_BREAK,"NOTIFY_UPGRADEEQUIP_BREAK");
		reload_key(NOTIFY_SAFEAREA_ENTER,"NOTIFY_SAFEAREA_ENTER");
		reload_key(NOTIFY_SAFEAREA_LEAVE,"NOTIFY_SAFEAREA_LEAVE");
		reload_key(NOTIFY_STATUS_NO_DAMAGE,"NOTIFY_STATUS_NO_DAMAGE");
		reload_key(NOTIFY_STATUS_NO_DROP_ON_DIE,"NOTIFY_STATUS_NO_DROP_ON_DIE");
		reload_key(NOTIFY_PK_LEVEL_LIMIT,"NOTIFY_PK_LEVEL_LIMIT");
		reload_key(NOTIFY_IN_CHINA_LIMIT,"NOTIFY_IN_CHINA_LIMIT");
		reload_key(NOTIFY_GUILD_FULL,"NOTIFY_GUILD_FULL");
		reload_key(NOTIFY_GUILD_WAR_START,"NOTIFY_GUILD_WAR_START");
		reload_key(NOTIFY_RELIVE_STAND_NOT_ALLOW,"NOTIFY_RELIVE_STAND_NOT_ALLOW");
		reload_key(NOTIFY_GUILD_CREATE_LEVEL_LIMIT,"NOTIFY_GUILD_CREATE_LEVEL_LIMIT");
		reload_key(NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP,"NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP");
		reload_key(NOTIFY_GUILD_JOIN_LEVEL_LIMIT,"NOTIFY_GUILD_JOIN_LEVEL_LIMIT");
		reload_key(NOTIFY_SERVER_FULL,"NOTIFY_SERVER_FULL");
		reload_key(NOTIFY_STEEL_EQUIP_NO_MONEY,"NOTIFY_STEEL_EQUIP_NO_MONEY");
		reload_key(NOTIFY_STEEL_EQUIP_NO_BAG_ROOM,"NOTIFY_STEEL_EQUIP_NO_BAG_ROOM");
		reload_key(NOTIFY_STEEL_EQUIP_NO_LEVEL,"NOTIFY_STEEL_EQUIP_NO_LEVEL");
		reload_key(NOTIFY_STEEL_EQUIP_SUC,"NOTIFY_STEEL_EQUIP_SUC");
		reload_key(NOTIFY_ITEM_USE_BROKE,"NOTIFY_ITEM_USE_BROKE");
		reload_key(NOTIFY_ITEM_USE_GENDER_ERROR,"NOTIFY_ITEM_USE_GENDER_ERROR");
		reload_key(NOTIFY_ITEM_USE_JOB_ERROR,"NOTIFY_ITEM_USE_JOB_ERROR");
		reload_key(NOTIFY_ITEM_EXCHANGE_LV_LIMIT,"NOTIFY_ITEM_EXCHANGE_LV_LIMIT");

		reload_key(NOTIFY_HORN_HAVE_NO,"NOTIFY_HORN_HAVE_NO");
		reload_key(NOTIFY_WAR_KILL,"NOTIFY_WAR_KILL");
		reload_key(NOTIFY_WAR_KILL_RAM,"NOTIFY_WAR_KILL_RAM");
		reload_key(NOTIFY_NPC_SELL_DENY,"NOTIFY_NPC_SELL_DENY");
		reload_key(NOTIFY_GIFT,"NOTIFY_GIFT");
		reload_key(NOTIFY_ITEM_TIME_LIMIT_FULL,"NOTIFY_ITEM_TIME_LIMIT_FULL");
		reload_key(NOTIFY_CHATTRADE_SUC,"NOTIFY_CHATTRADE_SUC");
		reload_key(NOTIFY_MOXUESHI_EMPTY,"NOTIFY_MOXUESHI_EMPTY");
		reload_key(NOTIFY_MOXUESHI_UPGRADE_NO,"NOTIFY_MOXUESHI_UPGRADE_NO");

		reload_key(NOTIFY_FRIEND_AUTHTYPE_ERROR,"NOTIFY_FRIEND_AUTHTYPE_ERROR");
		reload_key(NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR,"NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR");
		reload_key(NOTIFY_FRIEND_OPERATER_ERROR,"NOTIFY_FRIEND_OPERATER_ERROR");
		reload_key(NOTIFY_FRIEND_TOO_MUCH,"NOTIFY_FRIEND_TOO_MUCH");
		reload_key(NOTIFY_ENEMY_TOO_MUCH,"NOTIFY_ENEMY_TOO_MUCH");
		reload_key(NOTIFY_BLACK_TOO_MUCH,"NOTIFY_BLACK_TOO_MUCH");
		reload_key(NOTIFY_FRIEND_DELETE,"NOTIFY_FRIEND_DELETE");
		reload_key(NOTIFY_FRIEND_ADD,"NOTIFY_FRIEND_ADD");
		reload_key(NOTIFY_FRIEND_ADD_NOTIFY,"NOTIFY_FRIEND_ADD_NOTIFY");
		reload_key(NOTIFY_CANCEL_BY_TRADING,"NOTIFY_CANCEL_BY_TRADING");
		reload_key(NOTIFY_EXCUPD_FROM_NO_LEVEL,"NOTIFY_EXCUPD_FROM_NO_LEVEL");
		reload_key(NOTIFY_EXCUPD_TO_HAVE_LEVEL,"NOTIFY_EXCUPD_TO_HAVE_LEVEL");
		reload_key(NOTIFY_EXCUPD_BIND_TO_NOBIND,"NOTIFY_EXCUPD_BIND_TO_NOBIND");
		reload_key(NOTIFY_EXCUPD_EQUIP_TYPE_DIFF,"NOTIFY_EXCUPD_EQUIP_TYPE_DIFF");
		reload_key(NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW,"NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW");
		reload_key(NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH,"NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH");
		reload_key(NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH,"NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH");
		reload_key(NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN,"NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN");
		reload_key(NOTIFY_PK_KILL_SUB_LUCK,"NOTIFY_PK_KILL_SUB_LUCK");
		//reload_key(NOTIFY_UPGRADEEQUIP_PUBLISH_SUC,"NOTIFY_UPGRADEEQUIP_PUBLISH_SUC");
		//reload_key(NOTIFY_UPGRADEEQUIP_PUBLISH_FAIL,"NOTIFY_UPGRADEEQUIP_PUBLISH_FAIL");
		reload_key(NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN,"NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN");

		reload_key(NOTIFY_GAMEMONEY_ENOUGH, "NOTIFY_GAMEMONEY_ENOUGH");
		reload_key(NOTIFY_GAMEMONEYBIND_ENOUGH, "NOTIFY_GAMEMONEYBIND_ENOUGH");
		reload_key(NOTIFY_VCOIN_ENOUGH, "NOTIFY_VCOIN_ENOUGH");
		reload_key(NOTIFY_VCOINBIND_ENOUGH, "NOTIFY_VCOINBIND_ENOUGH");

		//reload_key(NOTIFY_MONSTER_DROP_ITEM,"NOTIFY_MONSTER_DROP_ITEM");
		//reload_key(NOTIFY_MONSTER_DROP_ITEM_NONAME,"NOTIFY_MONSTER_DROP_ITEM_NONAME");
		reload_key(NOTIFY_ADD_SLOT_MAX_LIMIT,"NOTIFY_ADD_SLOT_MAX_LIMIT");
		reload_key(NOTIFY_DART_OUT_TIME,"NOTIFY_DART_OUT_TIME");
		reload_key(NOTIFY_DART_OUT_RANGE_REMAIND,"NOTIFY_DART_OUT_RANGE_REMAIND");
		reload_key(NOTIFY_IS_DARTING,"NOTIFY_IS_DARTING");
		reload_key(NOTIFY_ACCEPT_DART_TASK,"NOTIFY_ACCEPT_DART_TASK");
		reload_key(NOTIFY_ROB_DART_NO_REWARD,"NOTIFY_ROB_DART_NO_REWARD");
		reload_key(NOTIFY_ROB_DART_REWARD,"NOTIFY_ROB_DART_REWARD");
		reload_key(NOTIFY_ROB_DART_NUMBER_FULL,"NOTIFY_ROB_DART_NUMBER_FULL");
		reload_key(NOTIFY_DART_DESTROYED,"NOTIFY_DART_DESTROYED");
		reload_key(NOTIFY_DART_DESTROYED_SUCCEED,"NOTIFY_DART_DESTROYED_SUCCEED");
		reload_key(NOTIFY_DART_SUCCEED,"NOTIFY_DART_SUCCEED");
		reload_key(NOTIFY_DIRECTFLY_FORBID_DARTING,"NOTIFY_DIRECTFLY_FORBID_DARTING");
		reload_key(NOTIFY_ACCEPT_DART_NUMBER_FULL,"NOTIFY_ACCEPT_DART_NUMBER_FULL");
		reload_key(NOTIFY_SKILL_FORBID_ROB_DART,"NOTIFY_SKILL_FORBID_ROB_DART");
		reload_key(NOTIFY_DIRECT_FLY_MAP_FORBID,"NOTIFY_DIRECT_FLY_MAP_FORBID");
		reload_key(NOTIFY_DIRECT_FLY_PKVALUE_FORBID,"NOTIFY_DIRECT_FLY_PKVALUE_FORBID");
		reload_key(NOTIFY_DIRECT_FLY_DEAD_FORBID,"NOTIFY_DIRECT_FLY_DEAD_FORBID");
		reload_key(NOTIFY_CDUPDITEM_VCOIN_FAIL,"NOTIFY_CDUPDITEM_VCOIN_FAIL");
		reload_key(NOTIFY_CANNOT_USE_LOTTERYDEPOT,"NOTIFY_CANNOT_USE_LOTTERYDEPOT");
		reload_key(NOTIFY_BAG_AND_DEPOT_FULL,"NOTIFY_BAG_AND_DEPOT_FULL");
		reload_key(NOTIFY_MAP_NO_INFO_PLAYER,"NOTIFY_MAP_NO_INFO_PLAYER");
		reload_key(NOTIFY_MAP_NO_INFO_CHAT,"NOTIFY_MAP_NO_INFO_CHAT");
		reload_key(NOTIFY_CAN_NOT_DEPOT, "NOTIFY_CAN_NOT_DEPOT");
		reload_key(NOTIFY_CAN_NOT_DESTORY, "NOTIFY_CAN_NOT_DESTORY");
		reload_key(NOTIFY_SAFEAREA_NO_DROP, "NOTIFY_SAFEAREA_NO_DROP");
		reload_key(NOTIFY_PK_VALUE_DESP, "NOTIFY_PK_VALUE_DESP");
		reload_key(NOTIFY_MAIL_TITLE, "NOTIFY_MAIL_TITLE");
		reload_key(NOTIFY_PLAYER_NOT_ONLINE_CHAT, "NOTIFY_PLAYER_NOT_ONLINE_CHAT");
		reload_key(NOTIFY_MAIL_CONTENT, "NOTIFY_MAIL_CONTENT");
		reload_key(NOTIFY_ANONYM_NAME, "NOTIFY_ANONYM_NAME");		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ONSALE_ITEM_SUC,"eee");//您寄售的%s已经被玩家%s买走.
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ONSALE_MIN_LEVEL_LIMIT,20);//"%d.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ITEM_TIME_LIMIT_FULL,"ss");//"%s物品使用时间限制.");,1
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_CHATTRADE_SUC,"ss","ss","ss");//"玩家 %s 的 %s 已经被玩家 %s 购买  
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_WORLD_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ROB_DART_REWARD,20);//"劫镖成功,您获得了 %d 经验值.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_DART_DESTROYED_SUCCEED,20);//"押镖完成,由于您的镖车已损坏，只能获得剩余的 %d 经验值");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_DART_SUCCEED,20);//"押镖成功,您获得了全部的 %d 经验值");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GROUP_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GUILD_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_NORMAL_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_MAP_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_HORN_CHAT_LEVEL_LIMIT,20);//"%d级后才可以发送世界消息.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_PK_KILLED,"eefe");//"你被 %s 杀死了");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_PK_KILL,"trest");//"你杀死了 %s");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_CONGZI_INFO,"eee",100);//"玩家 %s 通过商铺的元宝充值功能获得 %d 元宝");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN,100);//"元宝不足,开启新物品栅格需要消耗 %d 元宝");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GROUP_MEMBER_ADD,"eee");//"玩家 %s 加入队伍");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_JOIN_GROUP,"eee");//"你加入了 %s 的队伍.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GROUP_MEMBER_REM,"eee");//"玩家 %s 离开队伍");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GROUP_MEMBER_ONLINE,"eee");//"队员 %s 上线了.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GROUP_MEMBER_OFFLINE,"eee");//"队员 %s 已离线.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GUILD_MEMBER_ENTERING,"eee");//"玩家 %s 申请加入行会.");
		_snprintf_s(temp, _countof(temp),1023,NOTIFY_GUILD_ADD_PRESIDENT,"eee");//"玩家 %s 成为了行会长老.");
		_snprintf_s(temp, _countof(temp),1023,NOTIFY_GUILD_SUB_PRESIDENT, "eee");//"玩家 %s 被取消了长老资格."); 
		_snprintf_s(temp, _countof(temp),1023,NOTIFY_GUILD_BECOME_ADMIN, "eee");//"玩家 %s 成为了会长.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_CHATTRADE_SUBITEM_NOITEM,"eee");//"此商品已被玩家 %s 买走.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_PK_LEVEL_LIMIT,1000);//"等级低于 %d 级,不可以PK.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GUILD_CREATE_LEVEL_LIMIT,10);//"%d级以下不允许建立行会.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_CHATTRADE_MONEY_NOTENOUGH,10);//"交易失败,元宝不足:%d"); 
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_HUICHENGSHI_CISHU,10);//"回城石剩%d次使用机会");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GUILD_JOIN_LEVEL_LIMIT,100);//"%d级以下不允许加入行会.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ITEM_EXCHANGE_LV_LIMIT,100);//"%d 以下不可以使用装备兑换功能.");

		_snprintf_s(temp,_countof(temp),1023,NOTIFY_WAR_KILL,"eee","eee","ee","ee");//"%s 行会的 %s 在攻城战中击杀了 %s 行会的 %s.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_WAR_KILL_RAM,"ee","eee","eeee");//"%s 行会的 %s 在攻城战中歼灭了 %s 行会的攻城车.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_GIFT,"ee","ee");//"通过<font color='#FF0000'> %s </font>获得<font color='#FF0000'> %s </font>.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_FRIEND_DELETE,"ee");//"删除联系人 %s.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_FRIEND_ADD,"ee");//"添加联系人 %s.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_FRIEND_ADD_NOTIFY,"ee");//"%s 加你为好友.");
		_snprintf_s(temp,_countof(temp),1023,NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN,10);//"装备品级下降 %d.");

		

		return true;
	}
	void ConstsString::reload_key(char* dest,std::string key)
	{
		size_t slot_num=0;
		for(size_t i = 0;i < strlen(dest);i++)
		{
			if( dest[i] == '%' )
			{
				slot_num ++;
			}
		}
		StringMap::iterator pos = mStringMap.find(key);
		if( mStringMap.end() != pos )
		{
			size_t o=0;
			const char* p = pos->second.c_str();
			for(size_t i = 0;i < pos->second.length();i++)
			{
				if( p[i] == '%' )
				{
					o ++;
				}
			}
			if( o <= slot_num )
			{
				if( 0 != strcmp(dest,pos->second.c_str()) )
				{
					strcpy_s(dest,512,pos->second.c_str());
				}
			}
		}
		dest[511]=0;
	}
	bool ConstsString::ReLoad(GameServerLib* gslib)
	{
		LoadDefault();
		Load(gslib);
		return true;
	}
	bool ConstsString::LoadDefault()
	{
		char temp[1024];

		strcpy_s(NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP,"60级之前不能捡取");
		UtilString::act_2_utf8(NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP, strlen(NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP), temp, 1024);
		strcpy_s(NOTIFY_ITEM_LEVEL_LIMINT_CAN_NOT_PICK_UP, temp);

		strcpy_s(NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP,"一定时间内不能拾取");
		UtilString::act_2_utf8(NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP,strlen(NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP),temp,1024);
		strcpy_s(NOTIFY_ITEM_LOCK_CAN_NOT_PICK_UP,temp);

		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY,"金币不足,购买失败");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY,strlen(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEY,temp);

		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND,"银币不足,购买失败");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND,strlen(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_GAMEMONEYBIND,temp);

		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN,"元宝不足,购买失败");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN,strlen(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOIN,temp);

		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND,"金币不足,购买失败");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND,strlen(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_NOT_ENOPHY_VCOINBIND,temp);

		strcpy_s(NOTIFY_BING_ITEM_LIMIT,"绑定物品不可以寄售.");
		UtilString::act_2_utf8(NOTIFY_BING_ITEM_LIMIT,strlen(NOTIFY_BING_ITEM_LIMIT),temp,1024);
		strcpy_s(NOTIFY_BING_ITEM_LIMIT,temp);

		strcpy_s(NOTIFY_BEYOND_ONSALE_LIMIT,"您当前已达到寄售数量上限.");
		UtilString::act_2_utf8(NOTIFY_BEYOND_ONSALE_LIMIT,strlen(NOTIFY_BEYOND_ONSALE_LIMIT),temp,1024);
		strcpy_s(NOTIFY_BEYOND_ONSALE_LIMIT,temp);

		strcpy_s(NOTIFY_ONSALE_MAX_LIMIT,"系统当前寄售列表已超过百件，可以选择寄售其他物品.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_MAX_LIMIT,strlen(NOTIFY_ONSALE_MAX_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ONSALE_MAX_LIMIT,temp);

		strcpy_s(NOTIFY_ONSALE_PUT_SUC,"寄售成功，若成功售出将收取您5%的手续费，自己取回不收手续费.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_PUT_SUC,strlen(NOTIFY_ONSALE_PUT_SUC),temp,1024);
		strcpy_s(NOTIFY_ONSALE_PUT_SUC,temp);

		strcpy_s(NOTIFY_ONSALE_TIME_ERROR,"他人正在操作此物品，请稍后.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_TIME_ERROR,strlen(NOTIFY_ONSALE_TIME_ERROR),temp,1024);
		strcpy_s(NOTIFY_ONSALE_TIME_ERROR,temp);

		strcpy_s(NOTIFY_ONSALE_ITEM_MISS,"该物品已售出，已为您刷新列表，请重新选择.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_ITEM_MISS,strlen(NOTIFY_ONSALE_ITEM_MISS),temp,1024);
		strcpy_s(NOTIFY_ONSALE_ITEM_MISS,temp);

		strcpy_s(NOTIFY_ONSALE_OWNER_OFFLINE,"出售者已经下线，已经为您刷新列表，请重新选择.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_OWNER_OFFLINE,strlen(NOTIFY_ONSALE_OWNER_OFFLINE),temp,1024);
		strcpy_s(NOTIFY_ONSALE_OWNER_OFFLINE,temp);

		strcpy_s(NOTIFY_ONSALE_MIN_LEVEL_LIMIT,"寄售物品需等级达到%d级.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_MIN_LEVEL_LIMIT,strlen(NOTIFY_ONSALE_MIN_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ONSALE_MIN_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_ONSALE_ITEM_SUC,"您寄售的%s已经成功售出.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_ITEM_SUC,strlen(NOTIFY_ONSALE_ITEM_SUC),temp,1024);
		strcpy_s(NOTIFY_ONSALE_ITEM_SUC,temp);

		strcpy_s(NOTIFY_ONSALE_ITEM_CANNOT,"该物品不允许寄售.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_ITEM_CANNOT,strlen(NOTIFY_ONSALE_ITEM_CANNOT),temp,1024);
		strcpy_s(NOTIFY_ONSALE_ITEM_CANNOT,temp);

		strcpy_s(NOTIFY_ONSALE_FREE_LIMIT,"寄售需先交付%5的手续费.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_FREE_LIMIT,strlen(NOTIFY_ONSALE_FREE_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ONSALE_FREE_LIMIT,temp);

		strcpy_s(NOTIFY_ONSALE_MONEY_LIMIT,"寄售的金币需在1000-99999999之间,元宝需在10-999999之间.");
		UtilString::act_2_utf8(NOTIFY_ONSALE_MONEY_LIMIT,strlen(NOTIFY_ONSALE_MONEY_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ONSALE_MONEY_LIMIT,temp);

		strcpy_s(NOTIFY_USE_TIEM_LIMIT_ERROR,"不符合装备条件,装备失败");
		UtilString::act_2_utf8(NOTIFY_USE_TIEM_LIMIT_ERROR,strlen(NOTIFY_USE_TIEM_LIMIT_ERROR),temp,1024);
		strcpy_s(NOTIFY_USE_TIEM_LIMIT_ERROR,temp);

		strcpy_s(NOTIFY_ZHUANSHENG_LEVEL_LIMIT,"不符合转生等级要求,装备失败");
		UtilString::act_2_utf8(NOTIFY_ZHUANSHENG_LEVEL_LIMIT,strlen(NOTIFY_ZHUANSHENG_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ZHUANSHENG_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR,"装备不需要修理");
		UtilString::act_2_utf8(NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR,strlen(NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR),temp,1024);
		strcpy_s(NOTIFY_REPAIR_ITEM_NONEEDTOREPAIR,temp);

		strcpy_s(NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY,"金币不够,修理失败");
		UtilString::act_2_utf8(NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY,strlen(NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY),temp,1024);
		strcpy_s(NOTIFY_REPAIR_ITEM_NOT_ENOPHY_GAMEMONEY,temp);

		strcpy_s(NOTIFY_ITEM_TIME_LIMIT_FULL,"你拥有的 %s 的使用时间已到，已被系统自动收回.");//你拥有的 %s 的 %d 分钟的使用时间已到，已被系统自动收回.
		UtilString::act_2_utf8(NOTIFY_ITEM_TIME_LIMIT_FULL,strlen(NOTIFY_ITEM_TIME_LIMIT_FULL),temp,1024);
		strcpy_s(NOTIFY_ITEM_TIME_LIMIT_FULL,temp);

		strcpy_s(NOTIFY_MOXUESHI_EMPTY,"您的魔血石已用完，被系统回收.");
		UtilString::act_2_utf8(NOTIFY_MOXUESHI_EMPTY,strlen(NOTIFY_MOXUESHI_EMPTY),temp,1024);
		strcpy_s(NOTIFY_MOXUESHI_EMPTY,temp);

		strcpy_s(NOTIFY_MOXUESHI_UPGRADE_NO,"该物品不可以强化.");
		UtilString::act_2_utf8(NOTIFY_MOXUESHI_UPGRADE_NO,strlen(NOTIFY_MOXUESHI_UPGRADE_NO),temp,1024);
		strcpy_s(NOTIFY_MOXUESHI_UPGRADE_NO,temp);

		strcpy_s(NOTIFY_NOENOUGHMONEY_FAL,"金币不足.");
		UtilString::act_2_utf8(NOTIFY_NOENOUGHMONEY_FAL,strlen(NOTIFY_NOENOUGHMONEY_FAL),temp,1024);
		strcpy_s(NOTIFY_NOENOUGHMONEY_FAL,temp);

		strcpy_s(NOTIFY_UPGRADE_MATCHSTONE_FAL,"装备强化需要匹配当前等级的宝石.");
		UtilString::act_2_utf8(NOTIFY_UPGRADE_MATCHSTONE_FAL,strlen(NOTIFY_UPGRADE_MATCHSTONE_FAL),temp,1024);
		strcpy_s(NOTIFY_UPGRADE_MATCHSTONE_FAL,temp);

		strcpy_s(NOTIFY_NOT_ENOUPH_MP,"魔法值不够");
		UtilString::act_2_utf8(NOTIFY_NOT_ENOUPH_MP,strlen(NOTIFY_NOT_ENOUPH_MP),temp,1024);
		strcpy_s(NOTIFY_NOT_ENOUPH_MP,temp);
		
		strcpy_s(NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP,"包裹已满,不可拾取");
		UtilString::act_2_utf8(NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP,strlen(NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP),temp,1024);
		strcpy_s(NOTIFY_ITEM_SLOB_FULL_CAN_NOT_PICK_UP,temp);

		strcpy_s(NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN,"元宝不足,不能复活");
		UtilString::act_2_utf8(NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN,strlen(NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN),temp,1024);
		strcpy_s(NOTIFY_RELIVE_STAND_NOT_ENOUPH_VCOIN,temp);

		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP,"该地图不可丢弃物品");
		UtilString::act_2_utf8(NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP,strlen(NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP),temp,1024);
		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_ON_MAP,temp);

		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE,"游客玩家不可丢弃物品");
		UtilString::act_2_utf8(NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE,strlen(NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE),temp,1024);
		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_AUTH_TYPE,temp);

		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_BIND,"物品已绑定不可丢弃");
		UtilString::act_2_utf8(NOTIFY_DROP_ITEM_CAN_NOT_BIND,strlen(NOTIFY_DROP_ITEM_CAN_NOT_BIND),temp,1024);
		strcpy_s(NOTIFY_DROP_ITEM_CAN_NOT_BIND,temp);

		strcpy_s(NOTIFY_TRADE_ITEM_CAN_NOT_BIND,"物品已绑定不可交易");
		UtilString::act_2_utf8(NOTIFY_TRADE_ITEM_CAN_NOT_BIND,strlen(NOTIFY_TRADE_ITEM_CAN_NOT_BIND),temp,1024);
		strcpy_s(NOTIFY_TRADE_ITEM_CAN_NOT_BIND,temp);

		strcpy_s(NOTIFY_CHAT_TOO_QUICK,"发言过于频繁,请稍候再发");
		UtilString::act_2_utf8(NOTIFY_CHAT_TOO_QUICK,strlen(NOTIFY_CHAT_TOO_QUICK),temp,1024);
		strcpy_s(NOTIFY_CHAT_TOO_QUICK,temp);

		strcpy_s(NOTIFY_SKILL_YEMAN_FALIED,"冲撞力不足");
		UtilString::act_2_utf8(NOTIFY_SKILL_YEMAN_FALIED,strlen(NOTIFY_SKILL_YEMAN_FALIED),temp,1024);
		strcpy_s(NOTIFY_SKILL_YEMAN_FALIED,temp);

		strcpy_s(NOTIFY_SKILL_CISHAJIANSHU_OPEN,"刺杀剑气开启");
		UtilString::act_2_utf8(NOTIFY_SKILL_CISHAJIANSHU_OPEN,strlen(NOTIFY_SKILL_CISHAJIANSHU_OPEN),temp,1024);
		strcpy_s(NOTIFY_SKILL_CISHAJIANSHU_OPEN,temp);

		strcpy_s(NOTIFY_SKILL_CISHAJIANSHU_CLOSE,"刺杀剑气关闭");
		UtilString::act_2_utf8(NOTIFY_SKILL_CISHAJIANSHU_CLOSE,strlen(NOTIFY_SKILL_CISHAJIANSHU_CLOSE),temp,1024);
		strcpy_s(NOTIFY_SKILL_CISHAJIANSHU_CLOSE,temp);

		strcpy_s(NOTIFY_SKILL_BANYUEWANDAO_OPEN,"半月弯刀开启");
		UtilString::act_2_utf8(NOTIFY_SKILL_BANYUEWANDAO_OPEN,strlen(NOTIFY_SKILL_BANYUEWANDAO_OPEN),temp,1024);
		strcpy_s(NOTIFY_SKILL_BANYUEWANDAO_OPEN,temp);

		strcpy_s(NOTIFY_SKILL_BANYUEWANDAO_CLOSE,"半月弯刀关闭");
		UtilString::act_2_utf8(NOTIFY_SKILL_BANYUEWANDAO_CLOSE,strlen(NOTIFY_SKILL_BANYUEWANDAO_CLOSE),temp,1024);
		strcpy_s(NOTIFY_SKILL_BANYUEWANDAO_CLOSE,temp);

		strcpy_s(NOTIFY_SKILL_LIEHUOJIANFA_OK,"%s 召唤成功");
		UtilString::act_2_utf8(NOTIFY_SKILL_LIEHUOJIANFA_OK,strlen(NOTIFY_SKILL_LIEHUOJIANFA_OK),temp,1024);
		strcpy_s(NOTIFY_SKILL_LIEHUOJIANFA_OK,temp);

		strcpy_s(NOTIFY_SKILL_COLDING,"魔法冷却中");
		UtilString::act_2_utf8(NOTIFY_SKILL_COLDING,strlen(NOTIFY_SKILL_COLDING),temp,1024);
		strcpy_s(NOTIFY_SKILL_COLDING,temp);

		strcpy_s(NOTIFY_SKILL_SHUNJIANYIDONG_FAILED,"移动失败");
		UtilString::act_2_utf8(NOTIFY_SKILL_SHUNJIANYIDONG_FAILED,strlen(NOTIFY_SKILL_SHUNJIANYIDONG_FAILED),temp,1024);
		strcpy_s(NOTIFY_SKILL_SHUNJIANYIDONG_FAILED,temp);

		strcpy_s(NOTIFY_MERDER,"您犯了谋杀罪,并且增加100点PK值");
		UtilString::act_2_utf8(NOTIFY_MERDER,strlen(NOTIFY_MERDER),temp,1024);
		strcpy_s(NOTIFY_MERDER,temp);

		strcpy_s(NOTIFY_TRADE_TOO_FAR,"距离太远,不可以交易");
		UtilString::act_2_utf8(NOTIFY_TRADE_TOO_FAR,strlen(NOTIFY_TRADE_TOO_FAR),temp,1024);
		strcpy_s(NOTIFY_TRADE_TOO_FAR,temp);

		strcpy_s(NOTIFY_TRADE_CAN_NOT_AUTH_TYPE,"游客玩家不可以交易");
		UtilString::act_2_utf8(NOTIFY_TRADE_CAN_NOT_AUTH_TYPE,strlen(NOTIFY_TRADE_CAN_NOT_AUTH_TYPE),temp,1024);
		strcpy_s(NOTIFY_TRADE_CAN_NOT_AUTH_TYPE,temp);

		strcpy_s(NOTIFY_TRADE_CAN_NOT_LEVEL,"级以上玩家才可以进行交易");
		UtilString::act_2_utf8(NOTIFY_TRADE_CAN_NOT_LEVEL,strlen(NOTIFY_TRADE_CAN_NOT_LEVEL),temp,1024);
		strcpy_s(NOTIFY_TRADE_CAN_NOT_LEVEL,temp);

		strcpy_s(NOTIFY_ITEM_USE_TIME_TOO_SHORT,"物品使用过快");
		UtilString::act_2_utf8(NOTIFY_ITEM_USE_TIME_TOO_SHORT,strlen(NOTIFY_ITEM_USE_TIME_TOO_SHORT),temp,1024);
		strcpy_s(NOTIFY_ITEM_USE_TIME_TOO_SHORT,temp);

		strcpy_s(NOTIFY_BAG_USE_ITEM_MAP_DISABLED,"此地图禁止使用该物品");
		UtilString::act_2_utf8(NOTIFY_BAG_USE_ITEM_MAP_DISABLED,strlen(NOTIFY_BAG_USE_ITEM_MAP_DISABLED),temp,1024);
		strcpy_s(NOTIFY_BAG_USE_ITEM_MAP_DISABLED,temp);

		strcpy_s(NOTIFY_SKILL_MAP_DISABLED,"此地图禁止使用该技能");
		UtilString::act_2_utf8(NOTIFY_SKILL_MAP_DISABLED,strlen(NOTIFY_SKILL_MAP_DISABLED),temp,1024);
		strcpy_s(NOTIFY_SKILL_MAP_DISABLED,temp);

		strcpy_s(NOTIFY_MERGESTEEL_SUC,"玄铁精炼成功");
		UtilString::act_2_utf8(NOTIFY_MERGESTEEL_SUC,strlen(NOTIFY_MERGESTEEL_SUC),temp,1024);
		strcpy_s(NOTIFY_MERGESTEEL_SUC,temp);

		strcpy_s(NOTIFY_MERGESTEEL_FAL,"玄铁精炼失败");
		UtilString::act_2_utf8(NOTIFY_MERGESTEEL_FAL,strlen(NOTIFY_MERGESTEEL_FAL),temp,1024);
		strcpy_s(NOTIFY_MERGESTEEL_FAL,temp);

		strcpy_s(NOTIFY_UPGRADEEQUIP_SUC,"装备强化成功");
		UtilString::act_2_utf8(NOTIFY_UPGRADEEQUIP_SUC,strlen(NOTIFY_UPGRADEEQUIP_SUC),temp,1024);
		strcpy_s(NOTIFY_UPGRADEEQUIP_SUC,temp);

		strcpy_s(NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT,"限时装备不可以进行强化.");
		UtilString::act_2_utf8(NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT,strlen(NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT),temp,1024);
		strcpy_s(NOTIFY_UPGRADEEQUIP_LASTTIME_LIMIT,temp);

		strcpy_s(NOTIFY_QILING_SUC,"装备祈灵成功.");
		UtilString::act_2_utf8(NOTIFY_QILING_SUC,strlen(NOTIFY_QILING_SUC),temp,1024);
		strcpy_s(NOTIFY_QILING_SUC,temp);

		strcpy_s(NOTIFY_QILING_FULL,"可激活属性已满,不需要继续祈灵.");
		UtilString::act_2_utf8(NOTIFY_QILING_FULL,strlen(NOTIFY_QILING_FULL),temp,1024);
		strcpy_s(NOTIFY_QILING_FULL,temp);

		strcpy_s(NOTIFY_UPGRADEEQUIP_FAL,"装备强化失败");
		UtilString::act_2_utf8(NOTIFY_UPGRADEEQUIP_FAL,strlen(NOTIFY_UPGRADEEQUIP_FAL),temp,1024);
		strcpy_s(NOTIFY_UPGRADEEQUIP_FAL,temp);

		strcpy_s(NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT,"不满足装备使用条件,装备强化失败");
		UtilString::act_2_utf8(NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT,strlen(NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT),temp,1024);
		strcpy_s(NOTIFY_UPGRADEEQUIP_FAL_NEED_LIMIT,temp);

		strcpy_s(NOTIFY_BUY_ITEM_NOT_YOUKE,"游客模式不可以购买该商品");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_NOT_YOUKE,strlen(NOTIFY_BUY_ITEM_NOT_YOUKE),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_NOT_YOUKE,temp);

		strcpy_s(NOTIFY_SKILL_YOULINGDUN,"魔法防御增加");
		UtilString::act_2_utf8(NOTIFY_SKILL_YOULINGDUN,strlen(NOTIFY_SKILL_YOULINGDUN),temp,1024);
		strcpy_s(NOTIFY_SKILL_YOULINGDUN,temp);

		strcpy_s(NOTIFY_SKILL_SHENGZHANJIASHU,"物理防御增加");
		UtilString::act_2_utf8(NOTIFY_SKILL_SHENGZHANJIASHU,strlen(NOTIFY_SKILL_SHENGZHANJIASHU),temp,1024);
		strcpy_s(NOTIFY_SKILL_SHENGZHANJIASHU,temp);

		strcpy_s(NOTIFY_PK_MAP_NOT_MERDER,"PK地图不犯法");
		UtilString::act_2_utf8(NOTIFY_PK_MAP_NOT_MERDER,strlen(NOTIFY_PK_MAP_NOT_MERDER),temp,1024);
		strcpy_s(NOTIFY_PK_MAP_NOT_MERDER,temp);

		strcpy_s(NOTIFY_MAP_PK_PROHIBIT,"该地图不允许PK");
		UtilString::act_2_utf8(NOTIFY_MAP_PK_PROHIBIT,strlen(NOTIFY_MAP_PK_PROHIBIT),temp,1024);
		strcpy_s(NOTIFY_MAP_PK_PROHIBIT,temp);

		strcpy_s(NOTIFY_MAPTIME_PK_PROHIBIT, "准备阶段不允许PK");
		UtilString::act_2_utf8(NOTIFY_MAPTIME_PK_PROHIBIT, strlen(NOTIFY_MAPTIME_PK_PROHIBIT), temp, 1024);
		strcpy_s(NOTIFY_MAPTIME_PK_PROHIBIT, temp);

		strcpy_s(NOTIFY_WORLD_CHAT_LEVEL_LIMIT,"%d级后才可以发送世界消息.");
		UtilString::act_2_utf8(NOTIFY_WORLD_CHAT_LEVEL_LIMIT,strlen(NOTIFY_WORLD_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_WORLD_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_ROB_DART_REWARD,"劫镖成功,您获得了 %d 经验值.");
		UtilString::act_2_utf8(NOTIFY_ROB_DART_REWARD,strlen(NOTIFY_ROB_DART_REWARD),temp,1024);
		strcpy_s(NOTIFY_ROB_DART_REWARD,temp);

		strcpy_s(NOTIFY_DART_DESTROYED_SUCCEED,"你已经获得押镖任务的剩余奖励，获得 %d 经验值.");
		UtilString::act_2_utf8(NOTIFY_DART_DESTROYED_SUCCEED,strlen(NOTIFY_DART_DESTROYED_SUCCEED),temp,1024);
		strcpy_s(NOTIFY_DART_DESTROYED_SUCCEED,temp);

		strcpy_s(NOTIFY_DART_SUCCEED,"押镖成功,您获得了全部的 %d 经验值.");
		UtilString::act_2_utf8(NOTIFY_DART_SUCCEED,strlen(NOTIFY_DART_SUCCEED),temp,1024);
		strcpy_s(NOTIFY_DART_SUCCEED,temp);

		strcpy_s(NOTIFY_GROUP_CHAT_LEVEL_LIMIT,"%d级后才可以发送组队消息.");
		UtilString::act_2_utf8(NOTIFY_GROUP_CHAT_LEVEL_LIMIT,strlen(NOTIFY_GROUP_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_GROUP_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_GUILD_CHAT_LEVEL_LIMIT,"%d级后才可以发送行会消息.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CHAT_LEVEL_LIMIT,strlen(NOTIFY_GUILD_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_GUILD_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_NORMAL_CHAT_LEVEL_LIMIT,"%d级后才可以发送普通消息.");
		UtilString::act_2_utf8(NOTIFY_NORMAL_CHAT_LEVEL_LIMIT,strlen(NOTIFY_NORMAL_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_NORMAL_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_MAP_CHAT_LEVEL_LIMIT,"%d级后才可以发送喊话消息.");
		UtilString::act_2_utf8(NOTIFY_MAP_CHAT_LEVEL_LIMIT,strlen(NOTIFY_MAP_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_MAP_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT,"%d级后才可以发送私聊消息.");
		UtilString::act_2_utf8(NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT,strlen(NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_PRIVATE_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_HORN_CHAT_LEVEL_LIMIT,"%d级后才可以发送喇叭消息.");
		UtilString::act_2_utf8(NOTIFY_HORN_CHAT_LEVEL_LIMIT,strlen(NOTIFY_HORN_CHAT_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_HORN_CHAT_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_PK_KILLED,"你被 %s 杀死了");
		UtilString::act_2_utf8(NOTIFY_PK_KILLED,strlen(NOTIFY_PK_KILLED),temp,1024);
		strcpy_s(NOTIFY_PK_KILLED,temp);

		strcpy_s(NOTIFY_LOGIN_ANOTHER_PLACE,"此角色在其他终端登录,本会话关闭");
		UtilString::act_2_utf8(NOTIFY_LOGIN_ANOTHER_PLACE,strlen(NOTIFY_LOGIN_ANOTHER_PLACE),temp,1024);
		strcpy_s(NOTIFY_LOGIN_ANOTHER_PLACE,temp);

		strcpy_s(NOTIFY_FRESH_VCOIN_WAIT,"刷新过快,请稍候再试");
		UtilString::act_2_utf8(NOTIFY_FRESH_VCOIN_WAIT,strlen(NOTIFY_FRESH_VCOIN_WAIT),temp,1024);
		strcpy_s(NOTIFY_FRESH_VCOIN_WAIT,temp);

		strcpy_s(NOTIFY_KICK_BUY_GM,"你被强制下线");
		UtilString::act_2_utf8(NOTIFY_KICK_BUY_GM,strlen(NOTIFY_KICK_BUY_GM),temp,1024);
		strcpy_s(NOTIFY_KICK_BUY_GM,temp);

		strcpy_s(NOTIFY_TALK_PROHIBITED,"你已经被禁言");
		UtilString::act_2_utf8(NOTIFY_TALK_PROHIBITED,strlen(NOTIFY_TALK_PROHIBITED),temp,1024);
		strcpy_s(NOTIFY_TALK_PROHIBITED,temp);

		strcpy_s(NOTIFY_TALK_ALLOWED,"你的禁言已解除");
		UtilString::act_2_utf8(NOTIFY_TALK_ALLOWED,strlen(NOTIFY_TALK_ALLOWED),temp,1024);
		strcpy_s(NOTIFY_TALK_ALLOWED,temp);

		strcpy_s(NOTIFY_PK_KILL,"你杀死了 %s");
		UtilString::act_2_utf8(NOTIFY_PK_KILL,strlen(NOTIFY_PK_KILL),temp,1024);
		strcpy_s(NOTIFY_PK_KILL,temp);

		strcpy_s(NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD,"游客不可以创建行会");
		UtilString::act_2_utf8(NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD,strlen(NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD),temp,1024);
		strcpy_s(NOTIFY_YOUKE_CAN_NOT_CREATE_GUILD,temp);

		strcpy_s(NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD,"游客不可以加入行会");
		UtilString::act_2_utf8(NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD,strlen(NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD),temp,1024);
		strcpy_s(NOTIFY_YOUKE_CAN_NOT_JOIN_GUILD,temp);

		strcpy_s(NOTIFY_CONGZI_INFO,"玩家 %s 通过商铺的元宝充值功能获得 %d 元宝");
		UtilString::act_2_utf8(NOTIFY_CONGZI_INFO,strlen(NOTIFY_CONGZI_INFO),temp,1024);
		strcpy_s(NOTIFY_CONGZI_INFO,temp);

		strcpy_s(NOTIFY_BUY_ITEM_BAG_FULL,"包裹已满,不可以购买");
		UtilString::act_2_utf8(NOTIFY_BUY_ITEM_BAG_FULL,strlen(NOTIFY_BUY_ITEM_BAG_FULL),temp,1024);
		strcpy_s(NOTIFY_BUY_ITEM_BAG_FULL,temp);

		strcpy_s(NOTIFY_ITEM_BAG_FULL,"包裹已满.");
		UtilString::act_2_utf8(NOTIFY_ITEM_BAG_FULL,strlen(NOTIFY_ITEM_BAG_FULL),temp,1024);
		strcpy_s(NOTIFY_ITEM_BAG_FULL,temp);

		strcpy_s(NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN,"元宝不足,开启新物品栅格需要消耗 %d 元宝");
		UtilString::act_2_utf8(NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN,strlen(NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN),temp,1024);
		strcpy_s(NOTIFY_ADD_SLOT_NOT_ENOUPH_VCOIN,temp);

		strcpy_s(NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE,"游客模式不可以创建队伍");
		UtilString::act_2_utf8(NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE,strlen(NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE),temp,1024);
		strcpy_s(NOTIFY_GROUP_CREATE_FAIL_ERROR_AUTH_TYPE,temp);

		strcpy_s(NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE,"游客模式不可以加入队伍");
		UtilString::act_2_utf8(NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE,strlen(NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE),temp,1024);
		strcpy_s(NOTIFY_GROUP_JOIN_FAIL_ERROR_AUTH_TYPE,temp);

		strcpy_s(NOTIFY_GROUP_MEMBER_ADD,"玩家 %s 加入队伍");
		UtilString::act_2_utf8(NOTIFY_GROUP_MEMBER_ADD,strlen(NOTIFY_GROUP_MEMBER_ADD),temp,1024);
		strcpy_s(NOTIFY_GROUP_MEMBER_ADD,temp);

		strcpy_s(NOTIFY_JOIN_GROUP,"你加入了 %s 的队伍.");
		UtilString::act_2_utf8(NOTIFY_JOIN_GROUP,strlen(NOTIFY_JOIN_GROUP),temp,1024);
		strcpy_s(NOTIFY_JOIN_GROUP,temp);

		strcpy_s(NOTIFY_GROUP_MEMBER_REM,"玩家 %s 离开队伍");
		UtilString::act_2_utf8(NOTIFY_GROUP_MEMBER_REM,strlen(NOTIFY_GROUP_MEMBER_REM),temp,1024);
		strcpy_s(NOTIFY_GROUP_MEMBER_REM,temp);

		strcpy_s(NOTIFY_LEAVE_GROUP,"你已离开队伍");
		UtilString::act_2_utf8(NOTIFY_LEAVE_GROUP,strlen(NOTIFY_LEAVE_GROUP),temp,1024);
		strcpy_s(NOTIFY_LEAVE_GROUP,temp);

		strcpy_s(NOTIFY_TRADE_FAIL,"交易取消");
		UtilString::act_2_utf8(NOTIFY_TRADE_FAIL,strlen(NOTIFY_TRADE_FAIL),temp,1024);
		strcpy_s(NOTIFY_TRADE_FAIL,temp);

		strcpy_s(NOTIFY_TRADE_SUC,"交易成功");
		UtilString::act_2_utf8(NOTIFY_TRADE_SUC,strlen(NOTIFY_TRADE_SUC),temp,1024);
		strcpy_s(NOTIFY_TRADE_SUC,temp); 

		strcpy_s(NOTIFY_CHATTRADE_SUC,"玩家 %s 的 %s 已经被玩家 %s 购买");//"玩家 &s 的 %s 已经被玩家 %s 购买
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_SUC,strlen(NOTIFY_CHATTRADE_SUC),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_SUC,temp);

		strcpy_s(NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR,"卖家物品数据已修改,无法查看");
		UtilString::act_2_utf8(NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR,strlen(NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR),temp,1024);
		strcpy_s(NOTIFY_TRADE_PLAYER_ITEM_DATA_ERROR,temp); 

		strcpy_s(NOTIFY_TRADE_PLAYER_OFFLINE,"卖家已离线,暂停销售");
		UtilString::act_2_utf8(NOTIFY_TRADE_PLAYER_OFFLINE,strlen(NOTIFY_TRADE_PLAYER_OFFLINE),temp,1024);
		strcpy_s(NOTIFY_TRADE_PLAYER_OFFLINE,temp);  

		strcpy_s(NOTIFY_CHATTRADE_ADDITEM_SUC,"商品上架成功");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_ADDITEM_SUC,strlen(NOTIFY_CHATTRADE_ADDITEM_SUC),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_ADDITEM_SUC, temp); 

		strcpy_s(NOTIFY_NO_FRIEND_ONLINE, "您尚无好友在线");
		UtilString::act_2_utf8(NOTIFY_NO_FRIEND_ONLINE, strlen(NOTIFY_NO_FRIEND_ONLINE), temp, 1024);
		strcpy_s(NOTIFY_NO_FRIEND_ONLINE, temp);

		strcpy_s(NOTIFY_CHATTRADE_ADDITEM_FAIL,"商品上架失败");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_ADDITEM_FAIL,strlen(NOTIFY_CHATTRADE_ADDITEM_FAIL),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_ADDITEM_FAIL,temp);

		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_SUC,"商品下架成功,自动存入背包");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_SUBITEM_SUC,strlen(NOTIFY_CHATTRADE_SUBITEM_SUC),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_SUC,temp);

		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_FAIL,"商品下架失败,此商品已不存在");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_SUBITEM_FAIL,strlen(NOTIFY_CHATTRADE_SUBITEM_FAIL),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_FAIL,temp);

		strcpy_s(NOTIFY_CHATTRADE_MYSELF,"不允许自我交易");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_MYSELF,strlen(NOTIFY_CHATTRADE_MYSELF),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_MYSELF,temp);

		strcpy_s(NOTIFY_CHATTRADE_FAIL,"交易失败,此商品已下架");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_FAIL,strlen(NOTIFY_CHATTRADE_FAIL),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_FAIL, temp); 

		strcpy_s(NOTIFY_CHANGE_ATTACK_MODE_FAIL,"攻击模式已锁定,切换失败");
		UtilString::act_2_utf8(NOTIFY_CHANGE_ATTACK_MODE_FAIL,strlen(NOTIFY_CHANGE_ATTACK_MODE_FAIL),temp,1024);
		strcpy_s(NOTIFY_CHANGE_ATTACK_MODE_FAIL, temp); 

		strcpy_s(NOTIFY_MAP_NOGOD, "此地图禁止战神进入");
		UtilString::act_2_utf8(NOTIFY_MAP_NOGOD, strlen(NOTIFY_MAP_NOGOD), temp, 1024);
		strcpy_s(NOTIFY_MAP_NOGOD, temp);
		
		strcpy_s(NOTIFY_CHATTRADE_BAGFULL, "背包已满，请清理背包后继续交易");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_BAGFULL, strlen(NOTIFY_CHATTRADE_BAGFULL), temp, 1024);
		strcpy_s(NOTIFY_CHATTRADE_BAGFULL, temp);

		strcpy_s(NOTIFY_CHATTRADE_MONEY_NOTENOUGH,"交易失败,元宝不足:%d");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_MONEY_NOTENOUGH,strlen(NOTIFY_CHATTRADE_MONEY_NOTENOUGH),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_MONEY_NOTENOUGH, temp);  

		strcpy_s(NOTIFY_HUICHENGSHI_CISHU, "传送石剩余使用次数:%d");
		UtilString::act_2_utf8(NOTIFY_HUICHENGSHI_CISHU, strlen(NOTIFY_HUICHENGSHI_CISHU), temp, 1024);
		strcpy_s(NOTIFY_HUICHENGSHI_CISHU, temp);

		strcpy_s(NOTIFY_SLAVE_AI_OPEN,"宝宝自动攻击已打开,可以通过点击宝宝关闭");
		UtilString::act_2_utf8(NOTIFY_SLAVE_AI_OPEN,strlen(NOTIFY_SLAVE_AI_OPEN),temp,1024);
		strcpy_s(NOTIFY_SLAVE_AI_OPEN,temp);

		strcpy_s(NOTIFY_SLAVE_AI_CLOSE,"宝宝自动攻击已关闭,可以通过点击宝宝打开");
		UtilString::act_2_utf8(NOTIFY_SLAVE_AI_CLOSE,strlen(NOTIFY_SLAVE_AI_CLOSE),temp,1024);
		strcpy_s(NOTIFY_SLAVE_AI_CLOSE,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_EMPTY_NAME,"创建失败,行会名为空.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_EMPTY_NAME,strlen(NOTIFY_GUILD_CREATE_EMPTY_NAME),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_EMPTY_NAME,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_TOO_LONG_NAME,"创建失败,行会名称过长.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_TOO_LONG_NAME,strlen(NOTIFY_GUILD_CREATE_TOO_LONG_NAME),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_TOO_LONG_NAME,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_NAME_PROHIBITED,"创建失败,行会名称中包含非法字符.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_NAME_PROHIBITED,strlen(NOTIFY_GUILD_CREATE_NAME_PROHIBITED),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_NAME_PROHIBITED,temp);
		
		strcpy_s(NOTIFY_GUILD_CREATE_EXIST_NAME,"创建失败,该名字的行会已存在.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_EXIST_NAME,strlen(NOTIFY_GUILD_CREATE_EXIST_NAME),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_EXIST_NAME,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_CONDITION_FAIL,"创建失败,不满足创建行会的要求.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_CONDITION_FAIL,strlen(NOTIFY_GUILD_CREATE_CONDITION_FAIL),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_CONDITION_FAIL,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR,"创建失败,游客模式不可以创建行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR,strlen(NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_AUTH_TYPE_ERROR,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_HAVE_GUILD,"创建失败,已经拥有行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_HAVE_GUILD,strlen(NOTIFY_GUILD_CREATE_HAVE_GUILD),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_HAVE_GUILD,temp);

		strcpy_s(NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR,"加入行会失败,游客模式不可以加入行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR,strlen(NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR),temp,1024);
		strcpy_s(NOTIFY_GUILD_JOIN_AUTH_TYPE_ERROR,temp);

		strcpy_s(NOTIFY_GUILD_JOIN_HAVED,"加入行会失败,已经在行会中了.");
		UtilString::act_2_utf8(NOTIFY_GUILD_JOIN_HAVED,strlen(NOTIFY_GUILD_JOIN_HAVED),temp,1024);
		strcpy_s(NOTIFY_GUILD_JOIN_HAVED,temp);
		
		strcpy_s(NOTIFY_GUILD_JOIN_NOT_EXIST,"加入行会失败,行会不存在.");
		UtilString::act_2_utf8(NOTIFY_GUILD_JOIN_NOT_EXIST,strlen(NOTIFY_GUILD_JOIN_NOT_EXIST),temp,1024);
		strcpy_s(NOTIFY_GUILD_JOIN_NOT_EXIST,temp);

		strcpy_s(NOTIFY_GUILD_ADV_FULL,"只能存在四位副会长!");
		UtilString::act_2_utf8(NOTIFY_GUILD_ADV_FULL,strlen(NOTIFY_GUILD_ADV_FULL),temp,1024);
		strcpy_s(NOTIFY_GUILD_ADV_FULL,temp);

		strcpy_s(NOTIFY_MAIL_FULL, "邮件已达最大数目30,请先删除部分邮件方便接收新邮件!");
		UtilString::act_2_utf8(NOTIFY_MAIL_FULL, strlen(NOTIFY_MAIL_FULL), temp, 1024);
		strcpy_s(NOTIFY_MAIL_FULL, temp);

		strcpy_s(NOTIFY_GROUP_MEMBER_ONLINE,"队员 %s 上线了.");
		UtilString::act_2_utf8(NOTIFY_GROUP_MEMBER_ONLINE,strlen(NOTIFY_GROUP_MEMBER_ONLINE),temp,1024);
		strcpy_s(NOTIFY_GROUP_MEMBER_ONLINE,temp);

		strcpy_s(NOTIFY_GROUP_MEMBER_OFFLINE,"队员 %s 已离线.");
		UtilString::act_2_utf8(NOTIFY_GROUP_MEMBER_OFFLINE,strlen(NOTIFY_GROUP_MEMBER_OFFLINE),temp,1024);
		strcpy_s(NOTIFY_GROUP_MEMBER_OFFLINE,temp);

		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_NOITEM,"此商品已被玩家 %s 买走");
		UtilString::act_2_utf8(NOTIFY_CHATTRADE_SUBITEM_NOITEM,strlen(NOTIFY_CHATTRADE_SUBITEM_NOITEM),temp,1024);
		strcpy_s(NOTIFY_CHATTRADE_SUBITEM_NOITEM,temp);

		strcpy_s(NOTIFY_GUILD_MEMBER_ENTERING,"玩家 %s 申请加入行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_MEMBER_ENTERING,strlen(NOTIFY_GUILD_MEMBER_ENTERING),temp,1024);
		strcpy_s(NOTIFY_GUILD_MEMBER_ENTERING,temp);

		strcpy_s(NOTIFY_GUILD_ADD_PRESIDENT, "玩家 %s 成为了行会副会长.");
		UtilString::act_2_utf8(NOTIFY_GUILD_ADD_PRESIDENT, strlen(NOTIFY_GUILD_ADD_PRESIDENT), temp, 1024);
		strcpy_s(NOTIFY_GUILD_ADD_PRESIDENT, temp); 

		strcpy_s(NOTIFY_GUILD_SUB_PRESIDENT, " 玩家 %s 被取消了副会长资格.");
		UtilString::act_2_utf8(NOTIFY_GUILD_SUB_PRESIDENT, strlen(NOTIFY_GUILD_SUB_PRESIDENT), temp, 1024);
		strcpy_s(NOTIFY_GUILD_SUB_PRESIDENT, temp); 

		strcpy_s(NOTIFY_GUILD_BECOME_ADMIN, " 玩家 %s 成为了会长.");
		UtilString::act_2_utf8(NOTIFY_GUILD_BECOME_ADMIN, strlen(NOTIFY_GUILD_BECOME_ADMIN), temp, 1024);
		strcpy_s(NOTIFY_GUILD_BECOME_ADMIN, temp);

		strcpy_s(GUILD_RED_PACKET_MAIL_TITLE, "帮会红包退回");
		UtilString::act_2_utf8(GUILD_RED_PACKET_MAIL_TITLE, strlen(GUILD_RED_PACKET_MAIL_TITLE), temp, 1024);
		strcpy_s(GUILD_RED_PACKET_MAIL_TITLE, temp);

		strcpy_s(GUILD_RED_PACKET_MAIL_CONTENT, "退回红包");
		UtilString::act_2_utf8(GUILD_RED_PACKET_MAIL_CONTENT, strlen(GUILD_RED_PACKET_MAIL_CONTENT), temp, 1024);
		strcpy_s(GUILD_RED_PACKET_MAIL_CONTENT, temp);

		strcpy_s(NOTIFY_UPGRADEEQUIP_BREAK,"升级失败,装备破碎了.");
		UtilString::act_2_utf8(NOTIFY_UPGRADEEQUIP_BREAK,strlen(NOTIFY_UPGRADEEQUIP_BREAK),temp,1024);
		strcpy_s(NOTIFY_UPGRADEEQUIP_BREAK,temp);

		strcpy_s(NOTIFY_SAFEAREA_ENTER,"进入安全区.");
		UtilString::act_2_utf8(NOTIFY_SAFEAREA_ENTER,strlen(NOTIFY_SAFEAREA_ENTER),temp,1024);
		strcpy_s(NOTIFY_SAFEAREA_ENTER,temp);

		strcpy_s(NOTIFY_SAFEAREA_LEAVE,"离开安全区.");
		UtilString::act_2_utf8(NOTIFY_SAFEAREA_LEAVE,strlen(NOTIFY_SAFEAREA_LEAVE),temp,1024);
		strcpy_s(NOTIFY_SAFEAREA_LEAVE,temp);

		strcpy_s(NOTIFY_STATUS_NO_DAMAGE,"目标在无敌状态中,伤害被忽略.");
		UtilString::act_2_utf8(NOTIFY_STATUS_NO_DAMAGE,strlen(NOTIFY_STATUS_NO_DAMAGE),temp,1024);
		strcpy_s(NOTIFY_STATUS_NO_DAMAGE,temp);

		strcpy_s(NOTIFY_STATUS_NO_DROP_ON_DIE,"死亡物品保护状态中,没有掉落物品.");
		UtilString::act_2_utf8(NOTIFY_STATUS_NO_DROP_ON_DIE,strlen(NOTIFY_STATUS_NO_DROP_ON_DIE),temp,1024);
		strcpy_s(NOTIFY_STATUS_NO_DROP_ON_DIE,temp);

		strcpy_s(NOTIFY_PK_LEVEL_LIMIT,"等级低于 %d 级,不可以PK.");
		UtilString::act_2_utf8(NOTIFY_PK_LEVEL_LIMIT,strlen(NOTIFY_PK_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_PK_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_IN_CHINA_LIMIT,"您已被纳入防沉迷系统");
		UtilString::act_2_utf8(NOTIFY_IN_CHINA_LIMIT,strlen(NOTIFY_IN_CHINA_LIMIT),temp,1024);
		strcpy_s(NOTIFY_IN_CHINA_LIMIT,temp);

		strcpy_s(NOTIFY_GUILD_FULL,"行会人数超过上限,不可以再加入行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_FULL,strlen(NOTIFY_GUILD_FULL),temp,1024);
		strcpy_s(NOTIFY_GUILD_FULL,temp);

		strcpy_s(NOTIFY_GUILD_WAR_START,"本帮已于%s发起帮会战.");
		UtilString::act_2_utf8(NOTIFY_GUILD_WAR_START,strlen(NOTIFY_GUILD_WAR_START),temp,1024);
		strcpy_s(NOTIFY_GUILD_WAR_START,temp);

		strcpy_s(NOTIFY_RELIVE_STAND_NOT_ALLOW,"此地图禁止原地复活.");
		UtilString::act_2_utf8(NOTIFY_RELIVE_STAND_NOT_ALLOW,strlen(NOTIFY_RELIVE_STAND_NOT_ALLOW),temp,1024);
		strcpy_s(NOTIFY_RELIVE_STAND_NOT_ALLOW,temp);

		strcpy_s(NOTIFY_GUILD_CREATE_LEVEL_LIMIT,"%d级以下不允许建立行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_CREATE_LEVEL_LIMIT,strlen(NOTIFY_GUILD_CREATE_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_GUILD_CREATE_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_GUILD_JOIN_LEVEL_LIMIT,"%d级以下不允许加入行会.");
		UtilString::act_2_utf8(NOTIFY_GUILD_JOIN_LEVEL_LIMIT,strlen(NOTIFY_GUILD_JOIN_LEVEL_LIMIT),temp,1024);
		strcpy_s(NOTIFY_GUILD_JOIN_LEVEL_LIMIT,temp);

		strcpy_s(NOTIFY_SERVER_FULL,"本服务器已爆满,为了您可以流畅游戏,请选择其他区服游戏.");
		UtilString::act_2_utf8(NOTIFY_SERVER_FULL,strlen(NOTIFY_SERVER_FULL),temp,1024);
		strcpy_s(NOTIFY_SERVER_FULL,temp);

		strcpy_s(NOTIFY_STEEL_EQUIP_NO_MONEY,"金币不足,不可以拆解装备.");
		UtilString::act_2_utf8(NOTIFY_STEEL_EQUIP_NO_MONEY,strlen(NOTIFY_STEEL_EQUIP_NO_MONEY),temp,1024);
		strcpy_s(NOTIFY_STEEL_EQUIP_NO_MONEY,temp);

		strcpy_s(NOTIFY_STEEL_EQUIP_NO_BAG_ROOM,"包裹空间不足,不可以拆解装备.");
		UtilString::act_2_utf8(NOTIFY_STEEL_EQUIP_NO_BAG_ROOM,strlen(NOTIFY_STEEL_EQUIP_NO_BAG_ROOM),temp,1024);
		strcpy_s(NOTIFY_STEEL_EQUIP_NO_BAG_ROOM,temp);

		strcpy_s(NOTIFY_STEEL_EQUIP_NO_LEVEL,"装备未升级,不可以拆解装备.");
		UtilString::act_2_utf8(NOTIFY_STEEL_EQUIP_NO_LEVEL,strlen(NOTIFY_STEEL_EQUIP_NO_LEVEL),temp,1024);
		strcpy_s(NOTIFY_STEEL_EQUIP_NO_LEVEL,temp);

		strcpy_s(NOTIFY_STEEL_EQUIP_SUC,"宝石拆分成功.");
		UtilString::act_2_utf8(NOTIFY_STEEL_EQUIP_SUC,strlen(NOTIFY_STEEL_EQUIP_SUC),temp,1024);
		strcpy_s(NOTIFY_STEEL_EQUIP_SUC,temp);

		strcpy_s(NOTIFY_ITEM_USE_BROKE,"物品已损坏,请修理后再装备.");
		UtilString::act_2_utf8(NOTIFY_ITEM_USE_BROKE,strlen(NOTIFY_ITEM_USE_BROKE),temp,1024);
		strcpy_s(NOTIFY_ITEM_USE_BROKE,temp);

		strcpy_s(NOTIFY_MERGE_FASHION_CONDITION_FAIL,"只有两件永久武器时装、两件永久衣服时装才可以合成稀有时装.");
		UtilString::act_2_utf8(NOTIFY_MERGE_FASHION_CONDITION_FAIL,strlen(NOTIFY_MERGE_FASHION_CONDITION_FAIL),temp,1024);
		strcpy_s(NOTIFY_MERGE_FASHION_CONDITION_FAIL,temp);

		strcpy_s(NOTIFY_MERGE_XYFASHION_CONDITION_FAIL,"稀有时装不能再参与合成.");
		UtilString::act_2_utf8(NOTIFY_MERGE_XYFASHION_CONDITION_FAIL,strlen(NOTIFY_MERGE_XYFASHION_CONDITION_FAIL),temp,1024);
		strcpy_s(NOTIFY_MERGE_XYFASHION_CONDITION_FAIL,temp);

		strcpy_s(NOTIFY_ITEM_DESTORY_LIMIT_FAIL,"该物品不能被主动销毁.");
		UtilString::act_2_utf8(NOTIFY_ITEM_DESTORY_LIMIT_FAIL,strlen(NOTIFY_ITEM_DESTORY_LIMIT_FAIL),temp,1024);
		strcpy_s(NOTIFY_ITEM_DESTORY_LIMIT_FAIL,temp);

		strcpy_s(NOTIFY_ITEM_USE_GENDER_ERROR,"性别不匹配,装备失败.");
		UtilString::act_2_utf8(NOTIFY_ITEM_USE_GENDER_ERROR,strlen(NOTIFY_ITEM_USE_GENDER_ERROR),temp,1024);
		strcpy_s(NOTIFY_ITEM_USE_GENDER_ERROR,temp);

		strcpy_s(NOTIFY_ITEM_USE_JOB_ERROR,"职业不匹配,装备失败.");
		UtilString::act_2_utf8(NOTIFY_ITEM_USE_JOB_ERROR,strlen(NOTIFY_ITEM_USE_JOB_ERROR),temp,1024);
		strcpy_s(NOTIFY_ITEM_USE_JOB_ERROR,temp);

		strcpy_s(NOTIFY_ITEM_EXCHANGE_LV_LIMIT,"%d 以下不可以使用装备兑换功能.");
		UtilString::act_2_utf8(NOTIFY_ITEM_EXCHANGE_LV_LIMIT,strlen(NOTIFY_ITEM_EXCHANGE_LV_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ITEM_EXCHANGE_LV_LIMIT,temp);

		strcpy_s(NOTIFY_ADD_FRIEND_NO_EXIST,"该玩家不在线或不存在，不能添加.");
		UtilString::act_2_utf8(NOTIFY_ADD_FRIEND_NO_EXIST,strlen(NOTIFY_ADD_FRIEND_NO_EXIST),temp,1024);
		strcpy_s(NOTIFY_ADD_FRIEND_NO_EXIST,temp);

		strcpy_s(NOTIFY_CHECK_EQUIP_NO_EXIST,"该玩家不在线，不能查看装备.");
		UtilString::act_2_utf8(NOTIFY_CHECK_EQUIP_NO_EXIST,strlen(NOTIFY_CHECK_EQUIP_NO_EXIST),temp,1024);
		strcpy_s(NOTIFY_CHECK_EQUIP_NO_EXIST,temp);

		//strcpy_s(NOTIFY_CHINA_LIMIT_OK,"防沉迷信息已提交成功.");
		//UtilString::act_2_utf8(NOTIFY_CHINA_LIMIT_OK,strlen(NOTIFY_CHINA_LIMIT_OK),temp,1024);
		//strcpy_s(NOTIFY_CHINA_LIMIT_OK,temp);

		//strcpy_s(NOTIFY_CHINA_LIMIT_GAMEMONEY_NOTIFY,"金币原始收益 %d,防沉迷后收益 %d.");
		//UtilString::act_2_utf8(NOTIFY_CHINA_LIMIT_GAMEMONEY_NOTIFY,strlen(NOTIFY_CHINA_LIMIT_GAMEMONEY_NOTIFY),temp,1024);
		//strcpy_s(NOTIFY_CHINA_LIMIT_GAMEMONEY_NOTIFY,temp);

		//strcpy_s(NOTIFY_CHINA_LIMIT_GAMEMONEYBIND_NOTIFY,"银币原始收益 %d,防沉迷后收益 %d.");
		//UtilString::act_2_utf8(NOTIFY_CHINA_LIMIT_GAMEMONEYBIND_NOTIFY,strlen(NOTIFY_CHINA_LIMIT_GAMEMONEYBIND_NOTIFY),temp,1024);
		//strcpy_s(NOTIFY_CHINA_LIMIT_GAMEMONEYBIND_NOTIFY,temp);

		//strcpy_s(NOTIFY_CHINA_LIMIT_VCOINBIND_NOTIFY,"绑定元宝原始收益 %d,防沉迷后收益 %d.");
		//UtilString::act_2_utf8(NOTIFY_CHINA_LIMIT_VCOINBIND_NOTIFY,strlen(NOTIFY_CHINA_LIMIT_VCOINBIND_NOTIFY),temp,1024);
		//strcpy_s(NOTIFY_CHINA_LIMIT_VCOINBIND_NOTIFY,temp);

		//strcpy_s(NOTIFY_CHINA_LIMIT_EXP_NOTIFY,"经验原始收益 %d,防沉迷后收益 %d.");
		//UtilString::act_2_utf8(NOTIFY_CHINA_LIMIT_EXP_NOTIFY,strlen(NOTIFY_CHINA_LIMIT_EXP_NOTIFY),temp,1024);
		//strcpy_s(NOTIFY_CHINA_LIMIT_EXP_NOTIFY,temp);

		strcpy_s(NOTIFY_HORN_HAVE_NO,"您的包裹中没有喇叭道具,请进入商城购买.");
		UtilString::act_2_utf8(NOTIFY_HORN_HAVE_NO,strlen(NOTIFY_HORN_HAVE_NO),temp,1024);
		strcpy_s(NOTIFY_HORN_HAVE_NO,temp);

		strcpy_s(NOTIFY_WAR_KILL,"%s 行会的 %s 在攻城战中击杀了 %s 行会的 %s.");
		UtilString::act_2_utf8(NOTIFY_WAR_KILL,strlen(NOTIFY_WAR_KILL),temp,1024);
		strcpy_s(NOTIFY_WAR_KILL,temp);

		strcpy_s(NOTIFY_WAR_KILL_RAM,"%s 行会的 %s 在攻城战中歼灭了 %s 行会的攻城车.");
		UtilString::act_2_utf8(NOTIFY_WAR_KILL_RAM,strlen(NOTIFY_WAR_KILL_RAM),temp,1024);
		strcpy_s(NOTIFY_WAR_KILL_RAM,temp);

		strcpy_s(NOTIFY_NPC_SELL_DENY,"该物品不可以回收.");
		UtilString::act_2_utf8(NOTIFY_NPC_SELL_DENY,strlen(NOTIFY_NPC_SELL_DENY),temp,1024);
		strcpy_s(NOTIFY_NPC_SELL_DENY,temp);

		strcpy_s(NOTIFY_GIFT,"通过<font color='#FF0000'> %s </font>获得<font color='#FF0000'> %s </font>.");
		UtilString::act_2_utf8(NOTIFY_GIFT,strlen(NOTIFY_GIFT),temp,1024);
		strcpy_s(NOTIFY_GIFT,temp);

		strcpy_s(NOTIFY_FRIEND_AUTHTYPE_ERROR,"游客模式不开放好友系统.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_AUTHTYPE_ERROR,strlen(NOTIFY_FRIEND_AUTHTYPE_ERROR),temp,1024);
		strcpy_s(NOTIFY_FRIEND_AUTHTYPE_ERROR,temp);

		strcpy_s(NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR,"好友请求已过期.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR,strlen(NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR),temp,1024);
		strcpy_s(NOTIFY_FRIEND_AGREE_TIMEOUT_ERROR,temp);

		strcpy_s(NOTIFY_FRIEND_OPERATER_ERROR,"联系人操作太过频繁,请稍后再试.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_OPERATER_ERROR,strlen(NOTIFY_FRIEND_OPERATER_ERROR),temp,1024);
		strcpy_s(NOTIFY_FRIEND_OPERATER_ERROR,temp);

		strcpy_s(NOTIFY_FRIEND_TOO_MUCH,"好友数量达到上限,好友总数不得超过99.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_TOO_MUCH,strlen(NOTIFY_FRIEND_TOO_MUCH),temp,1024);
		strcpy_s(NOTIFY_FRIEND_TOO_MUCH,temp);

		strcpy_s(NOTIFY_ENEMY_TOO_MUCH,"仇人数量达到上限,仇人总数不得超过99.");
		UtilString::act_2_utf8(NOTIFY_ENEMY_TOO_MUCH,strlen(NOTIFY_ENEMY_TOO_MUCH),temp,1024);
		strcpy_s(NOTIFY_ENEMY_TOO_MUCH,temp);

		strcpy_s(NOTIFY_BLACK_TOO_MUCH,"您的黑名单已达上限,请及时清理");
		UtilString::act_2_utf8(NOTIFY_BLACK_TOO_MUCH,strlen(NOTIFY_BLACK_TOO_MUCH),temp,1024);
		strcpy_s(NOTIFY_BLACK_TOO_MUCH,temp);

		strcpy_s(NOTIFY_FRIEND_DELETE,"删除联系人 %s.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_DELETE,strlen(NOTIFY_FRIEND_DELETE),temp,1024);
		strcpy_s(NOTIFY_FRIEND_DELETE,temp);

		strcpy_s(NOTIFY_FRIEND_ADD,"添加联系人 %s.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_ADD,strlen(NOTIFY_FRIEND_ADD),temp,1024);
		strcpy_s(NOTIFY_FRIEND_ADD,temp);

		strcpy_s(NOTIFY_FRIEND_ADD_NOTIFY,"%s 加你为好友.");
		UtilString::act_2_utf8(NOTIFY_FRIEND_ADD_NOTIFY,strlen(NOTIFY_FRIEND_ADD_NOTIFY),temp,1024);
		strcpy_s(NOTIFY_FRIEND_ADD_NOTIFY,temp);

		strcpy_s(NOTIFY_CANCEL_BY_TRADING,"交易中，操作取消.");
		UtilString::act_2_utf8(NOTIFY_CANCEL_BY_TRADING,strlen(NOTIFY_CANCEL_BY_TRADING),temp,1024);
		strcpy_s(NOTIFY_CANCEL_BY_TRADING,temp);

		strcpy_s(NOTIFY_EXCUPD_FROM_NO_LEVEL,"源装备没有强化,不可以熔合.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_FROM_NO_LEVEL,strlen(NOTIFY_EXCUPD_FROM_NO_LEVEL),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_FROM_NO_LEVEL,temp);

		strcpy_s(NOTIFY_EXCUPD_TO_HAVE_LEVEL,"目标装备已强化,不可以熔合.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_TO_HAVE_LEVEL,strlen(NOTIFY_EXCUPD_TO_HAVE_LEVEL),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_TO_HAVE_LEVEL,temp);

		strcpy_s(NOTIFY_EXCUPD_BIND_TO_NOBIND,"绑定装备不可以与非绑定装备熔合.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_BIND_TO_NOBIND,strlen(NOTIFY_EXCUPD_BIND_TO_NOBIND),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_BIND_TO_NOBIND,temp);

		strcpy_s(NOTIFY_EXCUPD_EQUIP_TYPE_DIFF,"装备类型不同不可以熔合.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_EQUIP_TYPE_DIFF,strlen(NOTIFY_EXCUPD_EQUIP_TYPE_DIFF),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_EQUIP_TYPE_DIFF,temp);

		strcpy_s(NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW,"保护道具等级太低,熔合取消.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW,strlen(NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_PROTECTITEM_LEVEL_TOO_LOW,temp);

		strcpy_s(NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH,"金币不足,熔合取消.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH,strlen(NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_EQUIP_GM_NOT_ENOUPH,temp);

		strcpy_s(NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH,"绑定元宝不足,熔合取消.");
		UtilString::act_2_utf8(NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH,strlen(NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH),temp,1024);
		strcpy_s(NOTIFY_EXCUPD_EQUIP_BV_NOT_ENOUPH,temp);

		strcpy_s(NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN,"装备品级下降 %d.");
		UtilString::act_2_utf8(NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN,strlen(NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN),temp,1024);
		strcpy_s(NOTIFY_ITEM_EXCHANGE_UPD_LEVEL_DOWN,temp);

		strcpy_s(NOTIFY_PK_KILL_SUB_LUCK,"你的武器被诅咒了.");
		UtilString::act_2_utf8(NOTIFY_PK_KILL_SUB_LUCK,strlen(NOTIFY_PK_KILL_SUB_LUCK),temp,1024);
		strcpy_s(NOTIFY_PK_KILL_SUB_LUCK,temp);

		strcpy_s(NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN,"元宝不足,不可以神佑");
		UtilString::act_2_utf8(NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN,strlen(NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN),temp,1024);
		strcpy_s(NOTIFY_PROTECT_ITEM_NOT_ENOUPH_VCOIN,temp);

		strcpy_s(NOTIFY_GAMEMONEY_ENOUGH, "您的金币已达到最大存储量！");
		UtilString::act_2_utf8(NOTIFY_GAMEMONEY_ENOUGH, strlen(NOTIFY_GAMEMONEY_ENOUGH), temp, 1024);
		strcpy_s(NOTIFY_GAMEMONEY_ENOUGH, temp);

		strcpy_s(NOTIFY_GAMEMONEYBIND_ENOUGH, "您的绑定金币已达到最大存储量");
		UtilString::act_2_utf8(NOTIFY_GAMEMONEYBIND_ENOUGH, strlen(NOTIFY_GAMEMONEYBIND_ENOUGH), temp, 1024);
		strcpy_s(NOTIFY_GAMEMONEYBIND_ENOUGH, temp);

		strcpy_s(NOTIFY_VCOIN_ENOUGH, "您的元宝已达到最大存储量");
		UtilString::act_2_utf8(NOTIFY_VCOIN_ENOUGH, strlen(NOTIFY_VCOIN_ENOUGH), temp, 1024);
		strcpy_s(NOTIFY_VCOIN_ENOUGH, temp);

		strcpy_s(NOTIFY_VCOINBIND_ENOUGH, "您的绑定元宝已达到最大存储量");
		UtilString::act_2_utf8(NOTIFY_VCOINBIND_ENOUGH, strlen(NOTIFY_VCOINBIND_ENOUGH), temp, 1024);
		strcpy_s(NOTIFY_VCOINBIND_ENOUGH, temp);

		strcpy_s(NOTIFY_MAIL_TITLE,"系统邮件");
		UtilString::act_2_utf8(NOTIFY_MAIL_TITLE,strlen(NOTIFY_MAIL_TITLE),temp,1024);
		strcpy_s(NOTIFY_MAIL_TITLE,temp);

		strcpy_s(NOTIFY_MAIL_CONTENT,"感谢你支持我们的游戏,我们会更好的提高游戏质量.");
		UtilString::act_2_utf8(NOTIFY_MAIL_CONTENT,strlen(NOTIFY_MAIL_CONTENT),temp,1024);
		strcpy_s(NOTIFY_MAIL_CONTENT,temp);

		strcpy_s(NOTIFY_ANONYM_NAME,"神秘人");
		UtilString::act_2_utf8(NOTIFY_ANONYM_NAME,strlen(NOTIFY_ANONYM_NAME),temp,1024);
		strcpy_s(NOTIFY_ANONYM_NAME,temp);

		strcpy_s(NOTIFY_PK_VALUE_DESP,"你的PK值增加了.PK值是一种惩罚机制,当PK值超过200时,死亡会掉落背包中的所有装备,在城市内会被守卫弓箭手攻击.");
		UtilString::act_2_utf8(NOTIFY_PK_VALUE_DESP,strlen(NOTIFY_PK_VALUE_DESP),temp,1024);
		strcpy_s(NOTIFY_PK_VALUE_DESP,temp);

		strcpy_s(NOTIFY_ADD_SLOT_MAX_LIMIT,"您当前最大开包裹数已满");
		UtilString::act_2_utf8(NOTIFY_ADD_SLOT_MAX_LIMIT,strlen(NOTIFY_ADD_SLOT_MAX_LIMIT),temp,1024);
		strcpy_s(NOTIFY_ADD_SLOT_MAX_LIMIT,temp);

		strcpy_s(NOTIFY_DART_OUT_TIME,"你领取的押镖任务已超时，任务失败.");
		UtilString::act_2_utf8(NOTIFY_DART_OUT_TIME,strlen(NOTIFY_DART_OUT_TIME),temp,1024);
		strcpy_s(NOTIFY_DART_OUT_TIME,temp);

		strcpy_s(NOTIFY_DART_OUT_RANGE_REMAIND,"你已经离开镖车，请尽快回去，否则镖车将不会移动！");
		UtilString::act_2_utf8(NOTIFY_DART_OUT_RANGE_REMAIND,strlen(NOTIFY_DART_OUT_RANGE_REMAIND),temp,1024);
		strcpy_s(NOTIFY_DART_OUT_RANGE_REMAIND,temp);

		strcpy_s(NOTIFY_IS_DARTING,"你当前已有押镖任务！");
		UtilString::act_2_utf8(NOTIFY_IS_DARTING,strlen(NOTIFY_IS_DARTING),temp,1024);
		strcpy_s(NOTIFY_IS_DARTING,temp);

		strcpy_s(NOTIFY_ACCEPT_DART_TASK,"你已经领取押镖任务.");
		UtilString::act_2_utf8(NOTIFY_ACCEPT_DART_TASK,strlen(NOTIFY_ACCEPT_DART_TASK),temp,1024);
		strcpy_s(NOTIFY_ACCEPT_DART_TASK,temp);

		strcpy_s(NOTIFY_ROB_DART_NO_REWARD,"镖车已毁坏，but你与镖主的等级差距大于11级，不能获得奖励.");
		UtilString::act_2_utf8(NOTIFY_ROB_DART_NO_REWARD,strlen(NOTIFY_ROB_DART_NO_REWARD),temp,1024);
		strcpy_s(NOTIFY_ROB_DART_NO_REWARD,temp);

		strcpy_s(NOTIFY_ROB_DART_NUMBER_FULL,"当天劫镖次数已满.");
		UtilString::act_2_utf8(NOTIFY_ROB_DART_NUMBER_FULL,strlen(NOTIFY_ROB_DART_NUMBER_FULL),temp,1024);
		strcpy_s(NOTIFY_ROB_DART_NUMBER_FULL,temp);

		strcpy_s(NOTIFY_DART_DESTROYED,"你的镖车已经损坏,可以继续前往押送目的地领取剩余奖励.");
		UtilString::act_2_utf8(NOTIFY_DART_DESTROYED,strlen(NOTIFY_DART_DESTROYED),temp,1024);
		strcpy_s(NOTIFY_DART_DESTROYED,temp);

		strcpy_s(NOTIFY_DIRECTFLY_FORBID_DARTING,"押镖过程中禁止传送！");
		UtilString::act_2_utf8(NOTIFY_DIRECTFLY_FORBID_DARTING,strlen(NOTIFY_DIRECTFLY_FORBID_DARTING),temp,1024);
		strcpy_s(NOTIFY_DIRECTFLY_FORBID_DARTING,temp);

		strcpy_s(NOTIFY_ACCEPT_DART_NUMBER_FULL,"你当天的领取押镖任务的次数已满！");
		UtilString::act_2_utf8(NOTIFY_ACCEPT_DART_NUMBER_FULL,strlen(NOTIFY_ACCEPT_DART_NUMBER_FULL),temp,1024);
		strcpy_s(NOTIFY_ACCEPT_DART_NUMBER_FULL,temp);

		strcpy_s(NOTIFY_SKILL_FORBID_ROB_DART,"劫镖时禁止使用该技能！");
		UtilString::act_2_utf8(NOTIFY_SKILL_FORBID_ROB_DART,strlen(NOTIFY_SKILL_FORBID_ROB_DART),temp,1024);
		strcpy_s(NOTIFY_SKILL_FORBID_ROB_DART,temp);

		strcpy_s(NOTIFY_DIRECT_FLY_MAP_FORBID,"该地图不可以传送.");
		UtilString::act_2_utf8(NOTIFY_DIRECT_FLY_MAP_FORBID,strlen(NOTIFY_DIRECT_FLY_MAP_FORBID),temp,1024);
		strcpy_s(NOTIFY_DIRECT_FLY_MAP_FORBID,temp);

		strcpy_s(NOTIFY_DIRECT_FLY_PKVALUE_FORBID,"红名时不可以传送.");
		UtilString::act_2_utf8(NOTIFY_DIRECT_FLY_PKVALUE_FORBID,strlen(NOTIFY_DIRECT_FLY_PKVALUE_FORBID),temp,1024);
		strcpy_s(NOTIFY_DIRECT_FLY_PKVALUE_FORBID,temp);

		strcpy_s(NOTIFY_DIRECT_FLY_DEAD_FORBID,"死亡状态时禁止传送.");
		UtilString::act_2_utf8(NOTIFY_DIRECT_FLY_DEAD_FORBID,strlen(NOTIFY_DIRECT_FLY_DEAD_FORBID),temp,1024);
		strcpy_s(NOTIFY_DIRECT_FLY_DEAD_FORBID,temp);

		strcpy_s(NOTIFY_CDUPDITEM_VCOIN_FAIL,"元宝不足.");
		UtilString::act_2_utf8(NOTIFY_CDUPDITEM_VCOIN_FAIL,strlen(NOTIFY_CDUPDITEM_VCOIN_FAIL),temp,1024);
		strcpy_s(NOTIFY_CDUPDITEM_VCOIN_FAIL,temp);

		strcpy_s(NOTIFY_CANNOT_USE_LOTTERYDEPOT,"该仓库不可存放物品");
		UtilString::act_2_utf8(NOTIFY_CANNOT_USE_LOTTERYDEPOT,strlen(NOTIFY_CANNOT_USE_LOTTERYDEPOT),temp,1024);
		strcpy_s(NOTIFY_CANNOT_USE_LOTTERYDEPOT,temp);

		strcpy_s(NOTIFY_BAG_AND_DEPOT_FULL,"背包和仓库均已满");
		UtilString::act_2_utf8(NOTIFY_BAG_AND_DEPOT_FULL,strlen(NOTIFY_BAG_AND_DEPOT_FULL),temp,1024);
		strcpy_s(NOTIFY_BAG_AND_DEPOT_FULL,temp);

		strcpy_s(NOTIFY_MAP_NO_INFO_PLAYER,"该活动地图禁止查看对方装备.");
		UtilString::act_2_utf8(NOTIFY_MAP_NO_INFO_PLAYER,strlen(NOTIFY_MAP_NO_INFO_PLAYER),temp,1024);
		strcpy_s(NOTIFY_MAP_NO_INFO_PLAYER,temp);

		strcpy_s(NOTIFY_MAP_NO_INFO_CHAT,"该活动地图禁止聊天.");
		UtilString::act_2_utf8(NOTIFY_MAP_NO_INFO_CHAT,strlen(NOTIFY_MAP_NO_INFO_CHAT),temp,1024);
		strcpy_s(NOTIFY_MAP_NO_INFO_CHAT,temp);

		strcpy_s(NOTIFY_SPLIT_BAG_FULL_FAIL,"包裹已满,请先清理包裹再进行拆分.");
		UtilString::act_2_utf8(NOTIFY_SPLIT_BAG_FULL_FAIL,strlen(NOTIFY_SPLIT_BAG_FULL_FAIL),temp,1024);
		strcpy_s(NOTIFY_SPLIT_BAG_FULL_FAIL,temp);

		strcpy_s(NOTIFY_MAIL_RECEIVE_SUC,"成功收取邮件附件.");
		UtilString::act_2_utf8(NOTIFY_MAIL_RECEIVE_SUC,strlen(NOTIFY_MAIL_RECEIVE_SUC),temp,1024);
		strcpy_s(NOTIFY_MAIL_RECEIVE_SUC,temp);

		strcpy_s(NOTIFY_MAIL_HAVE_RECEIVED,"您已领取过此邮件附件.");
		UtilString::act_2_utf8(NOTIFY_MAIL_HAVE_RECEIVED,strlen(NOTIFY_MAIL_HAVE_RECEIVED),temp,1024);
		strcpy_s(NOTIFY_MAIL_HAVE_RECEIVED,temp);

		strcpy_s(NOTIFY_MAIL_DELETE_SUC,"成功删除邮件.");
		UtilString::act_2_utf8(NOTIFY_MAIL_DELETE_SUC,strlen(NOTIFY_MAIL_DELETE_SUC),temp,1024);
		strcpy_s(NOTIFY_MAIL_DELETE_SUC,temp);

		strcpy_s(NOTIFY_MAIL_EXCEED_MAX_LENGTH,"邮件标题或者邮件内容超出了最大长度.");
		UtilString::act_2_utf8(NOTIFY_MAIL_EXCEED_MAX_LENGTH,strlen(NOTIFY_MAIL_EXCEED_MAX_LENGTH),temp,1024);
		strcpy_s(NOTIFY_MAIL_EXCEED_MAX_LENGTH,temp);

		strcpy_s(NOTIFY_MAIL_DELETE_UNRECEIVED,"邮件附件未收取,不能删除.");
		UtilString::act_2_utf8(NOTIFY_MAIL_DELETE_UNRECEIVED,strlen(NOTIFY_MAIL_DELETE_UNRECEIVED),temp,1024);
		strcpy_s(NOTIFY_MAIL_DELETE_UNRECEIVED,temp);

		strcpy_s(NOTIFY_MAIL_NOT_EXIST,"邮件不存在.");
		UtilString::act_2_utf8(NOTIFY_MAIL_NOT_EXIST,strlen(NOTIFY_MAIL_NOT_EXIST),temp,1024);
		strcpy_s(NOTIFY_MAIL_NOT_EXIST,temp);

		strcpy_s(NOTIFY_BAG_BLANK_NOT_ENOUGH,"背包空格不足 %d 格,无法获得物品,请清理！");
		UtilString::act_2_utf8(NOTIFY_BAG_BLANK_NOT_ENOUGH,strlen(NOTIFY_BAG_BLANK_NOT_ENOUGH),temp,1024);
		strcpy_s(NOTIFY_BAG_BLANK_NOT_ENOUGH,temp);
		
		strcpy_s(NOTIFY_STALL_STOP,"摆摊停止");
		UtilString::act_2_utf8(NOTIFY_STALL_STOP,strlen(NOTIFY_STALL_STOP),temp,1024);
		strcpy_s(NOTIFY_STALL_STOP,temp);

		strcpy_s(NOTIFY_STALL_ITEM_FULL,"摊位已满,无法添加物品");
		UtilString::act_2_utf8(NOTIFY_STALL_ITEM_FULL,strlen(NOTIFY_STALL_ITEM_FULL),temp,1024);
		strcpy_s(NOTIFY_STALL_ITEM_FULL,temp);

		strcpy_s(NOTIFY_STALL_NO_ACTION,"摆摊中无法进行操作");
		UtilString::act_2_utf8(NOTIFY_STALL_NO_ACTION,strlen(NOTIFY_STALL_NO_ACTION),temp,1024);
		strcpy_s(NOTIFY_STALL_NO_ACTION,temp);

		strcpy_s(NOTIFY_STALL_NAME_ERROR,"错误的摊位名");
		UtilString::act_2_utf8(NOTIFY_STALL_NAME_ERROR,strlen(NOTIFY_STALL_NAME_ERROR),temp,1024);
		strcpy_s(NOTIFY_STALL_NAME_ERROR,temp);

		strcpy_s(NOTIFY_CAN_NOT_DEPOT,"该物品不可放入仓库.");
		UtilString::act_2_utf8(NOTIFY_CAN_NOT_DEPOT,strlen(NOTIFY_CAN_NOT_DEPOT),temp,1024);
		strcpy_s(NOTIFY_CAN_NOT_DEPOT,temp);

		strcpy_s(NOTIFY_CAN_NOT_DESTORY,"该物品不可摧毁.");
		UtilString::act_2_utf8(NOTIFY_CAN_NOT_DESTORY,strlen(NOTIFY_CAN_NOT_DESTORY),temp,1024);
		strcpy_s(NOTIFY_CAN_NOT_DESTORY,temp);

		strcpy_s(NOTIFY_SAFEAREA_NO_DROP,"安全区不可丢弃物品.");
		UtilString::act_2_utf8(NOTIFY_SAFEAREA_NO_DROP,strlen(NOTIFY_SAFEAREA_NO_DROP),temp,1024);
		strcpy_s(NOTIFY_SAFEAREA_NO_DROP,temp);

		strcpy_s(NOTIFY_PLAYER_NOT_ONLINE_CHAT,"玩家不在线,无法私聊.");
		UtilString::act_2_utf8(NOTIFY_PLAYER_NOT_ONLINE_CHAT,strlen(NOTIFY_PLAYER_NOT_ONLINE_CHAT),temp,1024);
		strcpy_s(NOTIFY_PLAYER_NOT_ONLINE_CHAT,temp);
		
		return true;
	}
	void ConstsString::dest()
	{
	}
	ConstsString::ConstsString(void)
	{
		LoadDefault();
	}
	ConstsString::~ConstsString(void)
	{
	}
}